<?php
/**
 * @file
 * osha_lingua_tools module file
 */

/**
 * Implements hook_permission().
 */
function osha_lingua_tools_permission() {
  $permissions = array();
  $permissions['use linguatools autocomplete'] = array('title' => t("Use linguatools autocomplete"));
  $permissions['use linguatools forms'] = array('title' => t("Use linguatools forms"));
  $permissions['use linguatools forms for calls content'] = array('title' => t("Use linguatools forms for calls content"));
  return $permissions;
}

function linguatools_access($node) {
  global $user;
  $type = is_string($node) ? $node : $node->type;
  if ($type == 'calls') {
    if (user_access('use linguatools forms for calls content', $user)) {
      return TRUE;
    }
  }
  elseif (user_access('use linguatools forms', $user)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_menu().
 */
function osha_lingua_tools_menu() {

  $items['node/%node/linguatools'] = array(
    'title' => 'Lingua Tools',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_lingua_form'),
    'access callback' => 'linguatools_access',
    'access arguments' => array(1),

    'weight' => 7,
    'type' => MENU_LOCAL_TASK,
  );
  $items['publication/node/autocomplete'] = array(
    'title' => 'Ajax callback autocomplete node',
    'description' => 'Ajax callback autocomplete node',
    'page callback' => 'osha_publication_node_autocomplete',
    'access arguments' => array('use linguatools autocomplete'),
    'type' => MENU_CALLBACK,
    'weight' => 2,
  );
  $items['admin/content/copy_publication_translation'] = array(
    'title' => 'Copy publication translation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('osha_copy_publication_translation'),
    'access arguments' => array('use linguatools forms'),
    'weight' => 8,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function osha_publication_node_autocomplete($string = '') {
  $matches = array();
  $result = db_select('node')
    ->fields('node', array('title', 'nid'))
    ->condition('type', 'publication')
    ->condition('title', '%' . db_like($string) . '%', 'LIKE')
    ->range(0, 20)
    ->execute();
  foreach ($result as $node) {
    $matches[$node->nid] = check_plain($node->title) . ' (' . $node->nid . ')';
  }
  drupal_json_output($matches);
}

function osha_copy_publication_translation($form, &$form_state) {
  $country_options = osha_lingua_tools_get_country_codes();
  drupal_add_js(drupal_get_path('module', 'osha_lingua_tools') . '/js/osha_lingua_tools.js');
  drupal_add_css(drupal_get_path('module', 'osha_lingua_tools') . '/css/osha_lingua_tools.css', array('group' => CSS_THEME));

  $form['node'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Choose a publication by title'),
    '#autocomplete_path' => 'publication/node/autocomplete',
  );
  $form['prefix_title'] = array(
    '#title' => 'Prefix title',
    '#type' => 'textfield',
    '#states' => array(
      'disabled' => array(
        '#edit-copy-option input[type="radio"]' => array('value' => 'one'),
      ),
    ),
  );
  $form['suffix_title'] = array(
    '#title' => 'Suffix title',
    '#type' => 'textfield',
    '#states' => array(
      'disabled' => array(
        '#edit-copy-option input[type="radio"]' => array('value' => 'one'),
      ),
    ),
  );
  $form['copy_option'] = array(
    '#type' => 'radios',
    '#title' => '',
    '#options' => array(
      'publication' => 'Publication',
      'one' => 'One publication for each country',
    ),
    '#default_value' => 'publication',
  );
  $form['publication_per_country'] = array(
    '#type' => 'fieldset',
  );
  $form['publication_per_country']['select_all_countries'] = array(
    '#type' => 'checkbox',
    '#title' => t('Select all countries'),
    '#states' => array(
      'disabled' => array(
        '#edit-copy-option input[type="radio"]' => array('value' => 'publication'),
      ),
    ),
  );
  $form['publication_per_country']['countries'] = array(
    '#type' => 'select',
    '#title' => '',
    '#options' => $country_options,
    '#multiple' => TRUE,
    '#chosen' => FALSE,
    '#size' => 20,
    '#states' => array(
      'disabled' => array(
        '#edit-copy-option input[type="radio"]' => array('value' => 'publication'),
      ),
    ),
  );

  $form['create'] = array(
    '#type' => 'submit',
    '#value' => t('Copy and translate'),
  );
  $form['preview'] = array(
    '#type' => 'submit',
    '#submit' => array('osha_copy_publication_translation_preview'),
    '#value' => t('Preview translations'),
  );
  if (isset($form_state['translation_info'])) {
    $form['#prefix'] = $form_state['translation_info'];
  }
  return $form;
}

function osha_copy_publication_translation_preview($form, &$form_state) {
  $source_node = node_load($form_state['values']['node']);

  $selected_languages = osha_copy_publication_translation_get_selected_languages($source_node);
  $rows = [];
  $header = array(t('Language'), t('Title'), t('Translated Title'));

  $prefix_title = $form_state['values']['prefix_title'];
  $suffix_title = $form_state['values']['suffix_title'];
  $copy_option = $form_state['values']['copy_option'];
  if ($copy_option == 'one') {
    $country_codes = osha_lingua_tools_get_country_codes();
    $countries = $form_state['values']['countries'];
    foreach ($countries as $country_code) {
      $selected_languages['en'] = 'English';
      foreach ($selected_languages as $lang_code => $lang_title) {
        if (isset($source_node->title_field[$lang_code])) {
          $title = $source_node->title_field[$lang_code][0]['value'];
          $country = $country_codes[$country_code];
          $new_title = osha_copy_publication_translation_get_title('', '', $title, $lang_code, $country);
          $rows[] = [$lang_title, $title, $new_title];
        }
      }
    }
  }
  else {
    foreach ($selected_languages as $lang_code => $lang_title) {
      if (isset($source_node->title_field[$lang_code])) {
        $title = $source_node->title_field[$lang_code][0]['value'];
        $new_title = osha_copy_publication_translation_get_title($prefix_title, $suffix_title, $title, $lang_code);
        $rows[] = [$lang_title, $title, $new_title];
      }
    }
  }
  $form_state['translation_info'] = '<h2>' . t('Preview titles:') . '</h2>';
  $form_state['translation_info'] .= theme('table', array('header' => $header, 'rows' => $rows));
  $form_state['rebuild'] = TRUE;
}

function osha_copy_publication_translation_get_title($prefix_title, $suffix_title, $title, $lang_code, $country = '') {
  if ($country) {
    $title = t(trim($country), [], ['langcode' => $lang_code]) . ' ' . $title;
  }
  if ($prefix_title) {
    $title = t(trim($prefix_title), [], ['langcode' => $lang_code]) . ' ' . $title;
  }
  if ($suffix_title) {
    $title .= ' ' . t(trim($suffix_title), [], ['langcode' => $lang_code]);
  }
  return $title;
}

function osha_copy_publication_translation_get_selected_languages($node) {
  $languages = tmgmt_available_languages();
  unset($languages[$node->translations->original]);
  return array_intersect_key($languages, osha_language_list_options());
}

function osha_copy_publication_translation_create_base_publication($title, $type, $source_node, $lang_code = 'en') {
  global $user;
  $node = new stdClass();
  $node->title = $title;
  $node->type = $type;
  node_object_prepare($node);

  $node->language = $lang_code;
  $node->uid = $user->uid;
  $node->status = 0;
  $node->promote = $source_node->promote;

  $fields = field_info_instances('node', $type);
  foreach ($fields as $field) {
    if (in_array($field['field_name'], ['field_file', 'field_publication_related_res', 'field_related_publications'])) {
      continue;
    }
    if (@$source_node->{$field['field_name']}[$lang_code]) {
      $node->{$field['field_name']}[$lang_code] = $source_node->{$field['field_name']}[$lang_code];
    }
    if (@$source_node->{$field['field_name']}[LANGUAGE_NONE]) {
      $node->{$field['field_name']}[LANGUAGE_NONE] = $source_node->{$field['field_name']}[LANGUAGE_NONE];
    }
  }
  $node->title_field[$node->language][0]['value'] = $title;
  $node->workbench_access = $source_node->workbench_access;
  $node = node_submit($node);
  node_save($node);
  return $node;
}

function osha_copy_publication_translation_submit($form, &$form_state) {
  $prefix_title = $form_state['values']['prefix_title'];
  $suffix_title = $form_state['values']['suffix_title'];
  $copy_option = $form_state['values']['copy_option'];
  $countries = $form_state['values']['countries'];
  if (!$prefix_title && !$suffix_title) {
    if (!$copy_option) {
      drupal_set_message(t('No prefix or suffix!'), 'error');
      return;
    }
  }
  if ($copy_option == 'one') {
    if (!$countries) {
      drupal_set_message(t('No countries selected!'), 'error');
      return;
    }
    return osha_lingua_tools_copy_one_publication_for_each_country($form, $form_state);
  }
  $nid = $form_state['values']['node'];
  osha_copy_publication_translation_original($nid, $form_state, $prefix_title, $suffix_title);
}

function osha_copy_publication_translation_original($nid, &$form_state, $prefix_title, $suffix_title, $country = '') {
  $source_node = node_load($nid);
  $source_lang = $source_node->translations->original;
  $source_title = $source_node->title_field[$source_lang][0]['value'];
  $languages = $source_node->title_field;
  unset($languages[$source_lang]);

  $rows = [];
  $header = array(t('Language'), t('New Title'), t('Old Title'));

  $new_title = osha_copy_publication_translation_get_title('', '', $source_title, $source_lang, $country);
  $node = osha_copy_publication_translation_create_base_publication($new_title, $source_node->type, $source_node, $source_lang);
  if (!$country) {
    drupal_set_message('Source ' . l($source_title,'node/' . $source_node->nid . '/translate') .' publication ' . $source_node->nid, 'status');
  }
  drupal_set_message('Created ' . l($new_title,'node/' . $node->nid . '/translate') .' publication (' . $source_lang . ') ' . $node->nid, 'status');

  if ($languages) {
    $translation_handler = entity_translation_get_handler('node', $node);
    foreach ($languages as $lang_code => $value) {
      if ($value) {
        $translation_handler->setTranslation(
          array(
            'translate' => 0,
            'status' => 1,
            'uid' => 1,
            'language' => $lang_code,
            'source' => $source_lang,
          )
        );
      }
    }
    $translation_handler->saveTranslations();
  }

  $node = workbench_moderation_node_current_load($node);
  $new_node = new stdClass();
  $new_node->id = $node->nid;
  $new_node->nid = $node->nid;
  $new_node->vid = $node->vid;
  $new_node->type = $source_node->type;
  $new_node->bundle = $source_node->type;
  $new_node->translations = $node->translations;

  $selected_languages = osha_copy_publication_translation_get_selected_languages($source_node);
  $fields = field_info_instances('node', $source_node->type);
  foreach ($languages as $lang_code => $value) {
    if ($value) {
      foreach ($fields as $field) {
        if (in_array($field['field_name'], ['field_file', 'field_publication_related_res', 'field_related_publications'])) {
          continue;
        }
        if ($field['field_name'] == 'title_field') {
          $source_title = $source_node->title_field[$lang_code][0]['value'];
          $new_title = osha_copy_publication_translation_get_title($prefix_title, $suffix_title, $source_title, $lang_code, $country);
          $rows[] = [$selected_languages[$lang_code], $new_title, $source_title];
          $new_node->{$field['field_name']}[$lang_code][0]['value'] = $new_title;
        }
        else {
          if (@$source_node->{$field['field_name']}[$lang_code]) {
            $new_node->{$field['field_name']}[$lang_code] = $source_node->{$field['field_name']}[$lang_code];
          }
          if (@$source_node->{$field['field_name']}[LANGUAGE_NONE]) {
            $new_node->{$field['field_name']}[LANGUAGE_NONE] = $source_node->{$field['field_name']}[LANGUAGE_NONE];
          }
        }
      }
    }
  }
  field_attach_update('node', $new_node);

  // Clone url_aliases.
  foreach ($languages as $lang_code => $value) {
    if ($value) {
      $args = array(
        'source' => 'node/' . $node->nid,
        'alias' => $node->path['alias'],
        'language' => $lang_code,
      );
      path_save($args);
    }
  }
  if ($rows) {
    if (empty($form_state['translation_info'])) {
      $form_state['translation_info'] = '';
    }
    $form_state['translation_info'] .= '<h2>' . t('Translated titles:') . '</h2>';
    $form_state['translation_info'] .= theme('table', array('header' => $header, 'rows' => $rows));
  }
  return $node;
}

/**
 * Implements hook_node_submit().
 */
function osha_lingua_tools_node_submit($node, $form, &$form_state) {
  // MC-73 When adding/deleting a file in english, it needs to be added/deleted
  // from other languages too.
  $old_node = $form['#node'];
  $fields = _osha_lingua_tools_translatable_field_instances($node->type);
  foreach ($fields as $field) {
    $fieldname = $field['field_name'];
    $diff = _osha_lingua_tools_filefield_diff($old_node, $node, $fieldname, 'en');
    $files_added = $diff['files_added'];
    $files_deleted = $diff['files_deleted'];

    if (!empty($files_deleted)) {
      foreach ($node->{$fieldname} as $lang => $items) {
        foreach ($items as $key => $item) {
          if (array_key_exists($item['fid'], $files_deleted)) {
            unset($node->{$fieldname}[$lang][$key]);
          }
        }
      }
    }
    if (!empty($files_added)) {
      foreach ($files_added as $file) {
        foreach ($node->{$fieldname} as $lang => &$items) {
          if ($lang == 'en') {
            continue;
          }
          $exists = FALSE;
          foreach ($items as $item) {
            if ($item['fid'] == $file['fid']) {
              $exists = TRUE;
              break;
            }
          }
          if (!$exists) {
            $items[] = $file;
          }
        }
      }
    }
  }
}

/**
 * Helper function to get the files added/deleted in a certain field after a
 * node save.
 *
 * @param $old_node
 * @param $new_node
 * @param $fieldname
 * @param string $language
 * @return array
 *  Array with files added/deleted.
 */
function _osha_lingua_tools_filefield_diff($old_node, $new_node, $fieldname, $language = 'en') {
  $files_added = $files_deleted = array();
  $old_node_elems = isset ($old_node->{$fieldname}[$language]) && !empty($old_node->{$fieldname}[$language]);
  $node_elems = isset ($new_node->{$fieldname}[$language]) && !empty($new_node->{$fieldname}[$language]);
  if ($old_node_elems) {
    foreach ($old_node->{$fieldname}[$language] as $key => $old_file) {
      $files_deleted[$old_file['fid']] = $old_node->{$fieldname}[$language][$key];
    }
    if ($node_elems) {
      foreach ($new_node->{$fieldname}[$language] as $key => $file) {
        if (array_key_exists($file['fid'], $files_deleted)) {
          unset($files_deleted[$file['fid']]);
        }
        else {
          $files_added[$file['fid']] = $new_node->{$fieldname}[$language][$key];
        }
      }
    }
  }
  elseif ($node_elems) {
    foreach ($new_node->{$fieldname}[$language] as $key => $file) {
      $files_added[$file['fid']] = $old_node->{$fieldname}[$language][$key];
    }
  }
  return array(
    'files_added' => $files_added,
    'files_deleted' => $files_deleted,
  );
}

function form_lingua_form($form, &$form_state) {
  $node = menu_get_object();
  $translated_in = array();
  $numlen = count($node->translations->data);

  if ($numlen <= 1) {
    $form['header_text'] = array(
      '#markup' => '<p class="linguaheader">There are no translations for this node.</p>',
      '#fieldintname' => '0',
    );
  }
  else {
    // Get the node id, what we want translate.
    $type = $node->type;
    $fields = field_info_instances("node", $type);
    $countfields = 1;
    $ispublished = $node->workbench_moderation['current']->published;

    foreach ($fields as $field) {
      $fieldname = $field['label'];
      $fieldname = str_replace(' ', '_', $fieldname);
      $fieldintname = $field['field_name'];
      $arrayfield = $node->$fieldintname;

      // TODO Check that the field has data.
      $numdatosfield = count($arrayfield) + 1;
      $fieldid = $field['field_id'];
      $transfield = istranslatable($fieldid);

      $form['header_text'] = array(
        '#markup' => '<p class="linguaheader">Please, select the fields to spread and press the <strong>spread data</strong> button.</p>',
        '#fieldintname' => '0',
      );
      if ($transfield == 1 && $field['widget']['module'] != 'media' && $field['widget']['module'] != 'file' && $field['widget']['module'] != 'pdf_to_image' && $numdatosfield > 0) {
        $countfields++;
        $form[$fieldname] = array(
          '#title' => $fieldname,
          '#type' => 'checkbox',
          '#fieldintname' => $fieldintname,
        );
      }
    }

    $form['url'] = array(
      '#title' => 'URL',
      '#type' => 'checkbox',
    );

    $form['submit_button'] = array(
      '#type' => 'submit',
      '#value' => t('Spread data'),
      '#numfields' => $countfields,
      '#nodeid' => $node->nid,
      '#noderevid' => $node->workbench_moderation['current']->vid,
      '#ispublished' => $ispublished,
    );
  }

  $languages = tmgmt_available_languages();
  unset($languages[$node->translations->original]);
  foreach ($node->translations->data as $lang => $translation) {
    $translated_in[$lang] = $languages[$lang];
    unset($languages[$lang]);
  }
  unset($translated_in['en']);
  $selected_languages = array_intersect_key($languages, osha_language_list_options());

  $form['target_language'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Add translations for'),
    '#multiple' => TRUE,
    '#options' => $languages,
    '#default_value' => array_keys($selected_languages),
    '#weight' => array('#weight' => 6),
  );
  $form['create_translations_submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Create translations'),
    '#submit' => array('osha_lingua_tools_create_translations'),
    '#weight' => array('#weight' => 7),
  );

  $fields = _osha_lingua_tools_translatable_field_instances($node->type);
  if (!empty($fields)) {
    $form['propagate_files_header_text'] = array(
      '#markup' => '<p class="linguaheader">Please, select the files to spread and the languages where to copy the files, then press the <strong>spread files</strong> button.</p>',
      '#weight' => array('#weight' => 8),
    );

    $form['spread_files_fields'] = array(
      '#weight' => array('#weight' => 9),
    );

    $form['spread_files_target_language'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Copy files to'),
      '#multiple' => TRUE,
      '#options' => $translated_in,
      '#default_value' => array_keys($translated_in),
      '#weight' => array('#weight' => 10),
    );

    $form['propagate_files_submit_button'] = array(
      '#type' => 'submit',
      '#value' => t('Spread files'),
      '#submit' => array('osha_lingua_tools_spread_files'),
      '#weight' => array('#weight' => 11),
    );
  }
  foreach ($fields as $field) {
    $files_to_copy = array();
    $selected_files = array();
    foreach ($node->{$field['field_name']}['en'] as $item) {
      $files_to_copy[$item['fid']] = $item['filename'];
      foreach ($translated_in as $lang => $language) {
        $found = FALSE;
        foreach ($node->{$field['field_name']}[$lang] as $translated_item) {
          if ($translated_item['fid'] == $item['fid']) {
            $found = TRUE;
            break;
          }
        }
        if (!$found) {
          $selected_files[$item['fid']] = [$item['fid']];
          break;
        }
      }
    }
    $form['spread_files_fields'][$field['field_name']] = array(
      '#type' => 'checkboxes',
      '#title' => $field['label'],
      '#multiple' => TRUE,
      '#options' => $files_to_copy,
      '#default_value' => array_keys($selected_files),
    );
  }

  return $form;
}

function istranslatable($idfield) {
  $result = db_select('field_config', 'f')
    ->fields('f', array('translatable'))
    ->condition('id', $idfield, '=')
    ->execute()
    ->fetchAssoc();
  return $result['translatable'];
}

function form_lingua_form_validate($form, &$form_state) {
  if ($form_state['triggering_element']['#id'] != 'edit-submit-button') {
    return;
  }

  foreach ($form_state['values'] as $values) {

    if ($values == 1) {
      return 1;
    }
  }
  drupal_set_message(t("You need to select at least one field for spread!"), 'error');
  return FALSE;
}

function form_lingua_form_submit($form, &$form_state) {
  $intnumfields = $form['submit_button']['#numfields'];
  $intnodeid = $form['submit_button']['#nodeid'];
  $intrevid = $form['submit_button']['#noderevid'];
  $ispublished = $form['submit_button']['#ispublished'];

  if ($form_state['values']['url'] == 1) {
    propage_url($intnodeid);
  }

  $intcont = 0;

  foreach ($form as $fieldchk) {
    $fieldintname = $fieldchk['#fieldintname'];
    // 0 Is the value of the summary field.
    if ($fieldintname <> '0') {

      $fieldupdate = $form_state['values'][$fieldchk['#title']];
      if ($fieldupdate) {
        propage_translation($fieldchk['#title'], $intnodeid, $intrevid, $ispublished, $fieldintname);
      }
    }
    $intcont++;
    if ($intcont == $intnumfields) {
      if ($ispublished == 1) {
        drupal_flush_all_caches();
      }
      break;
    }
  }
}

function propage_translation($field_name, $intnodeid, $intrevid, $ispublished, $fieldintname) {
  $node = node_load($intnodeid);

  if ($field_name == 'body') {
    $table_name = 'field_data_body';
    $table_rev_name = 'field_revision_body';
    $field_name = 'body_value';
  }
  elseif (($fieldintname == 'field_external_url') || ($fieldintname == 'field_banner_link')) {
    $table_name = 'field_data_' . $fieldintname;
    $table_rev_name = 'field_revision_' . $fieldintname;
    $field_name = $fieldintname . '_url';
  }
  else {
    $table_name = 'field_data_' . $fieldintname;
    $table_rev_name = 'field_revision_' . $fieldintname;
    $field_name = $fieldintname . '_value';
  }

  // If the status of the node is published then We get the value to spread from the data field else we get the data from the revision field.
  if ($ispublished == 1) {
    $result = db_select($table_name, 'f')
      ->fields('f', array($field_name))
      ->condition('entity_id', $intnodeid, '=')
      ->condition('language', 'en', '=')
      ->orderBy('revision_id', 'DESC')
      ->execute()
      ->fetchAssoc();
  }
  else {
    $result = db_select($table_rev_name, 'f')
      ->fields('f', array($field_name))
      ->condition('entity_id', $intnodeid, '=')
      ->condition('language', 'en', '=')
      ->orderBy('revision_id', 'DESC')
      ->execute()
      ->fetchAssoc();
  }
  $propvalue = $result[$field_name];

  if ($propvalue == "" || $propvalue == NULL) {
    return FALSE;
  }

  $new_node = new stdClass();
  $new_node->id = $node->nid;
  $new_node->nid = $node->nid;
  $new_node->vid = $node->vid;
  $new_node->type = $node->type;
  $new_node->bundle = $node->type;
  $new_node->translations = $node->translations;
  foreach ($node->translations->data as $lang_code => $value) {
    $new_node->{$fieldintname}[$lang_code] = $node->{$fieldintname}[$node->language];
  }
  field_attach_update('node', $new_node);

  drupal_set_message(t("Field " . $field_name . " updated"), 'status');

}

function propage_url($intnodeid) {
  $node = node_load($intnodeid);
  $propvalue = $node->path['alias'];

  $aliasurl = "node/" . $intnodeid;
  // Update the url field.
  $data = db_update('url_alias')
    ->fields(array(
      'alias' => $propvalue,
    ))
    ->condition('source', $aliasurl)
    ->execute();

  drupal_set_message(t("URL Alias updated"), 'status');
}

function osha_lingua_tools_create_translations($form, &$form_state) {
  $languages = $form_state['values']['target_language'];
  $node = menu_get_object();
  $source_lang = $node->translations->original;
  $translation_handler = entity_translation_get_handler('node', $node);
  $type = $node->type;
  $fields = _osha_lingua_tools_translatable_field_instances($type);
  foreach ($languages as $lang_code => $value) {
    if ($value) {
      $translation_handler->setTranslation(
        array(
          'translate' => 0,
          'status' => 1,
          'uid' => 1,
          'language' => $lang_code,
          'source' => $source_lang,
        )
      );
    }
  }
  $translation_handler->saveTranslations();

  $node = workbench_moderation_node_current_load($node);
  $new_node = new stdClass();
  $new_node->id = $node->nid;
  $new_node->nid = $node->nid;
  $new_node->vid = $node->vid;
  $new_node->type = $type;
  $new_node->bundle = $type;
  $new_node->translations = $node->translations;
  foreach ($languages as $lang_code => $value) {
    if ($value) {
      foreach ($fields as $field) {
        // MC-73 Copy values for translatable file fields.
        $new_node->{$field['field_name']}[$lang_code] = $node->{$field['field_name']}[$source_lang];
      }
    }
  }
  field_attach_update('node', $new_node);

  // Clone url_aliases.
  foreach ($languages as $lang_code => $value) {
    if ($value) {
      $args = array(
        'source' => 'node/' . $node->nid,
        'alias' => $node->path['alias'],
        'language' => $lang_code,
      );
      path_save($args);
    }
  }
}

/**
 * Helper function to get translatable fields with cardinality > 1.
 *
 * @param $bundle
 *  The type of the node to call field_info_instances().
 * @return array
 *  Array of fields.
 */
function _osha_lingua_tools_translatable_field_instances($bundle) {
  $translatable_fields = array();
  $fields = field_info_instances('node', $bundle);
  foreach ($fields as $field) {
    $fieldname = $field['field_name'];
    $transfield = istranslatable($field['field_id']);
    $info = field_info_field($fieldname);
    if ($transfield == 1
      && $field['widget']['module'] == 'file'
      && ($info['cardinality'] > 1 || $info['cardinality'] == FIELD_CARDINALITY_UNLIMITED)) {
      $translatable_fields[] = $field;
    }
  }
  return $translatable_fields;
}

/**
 * Copy the selected files from english to all selected languages.
 *
 * @param $form
 * @param $form_state
 */
function osha_lingua_tools_spread_files($form, &$form_state) {
  $node = menu_get_object();
  $fields = _osha_lingua_tools_translatable_field_instances($node->type);

  foreach ($fields as $field) {
    // Get files objects that needs to be copied.
    $items_to_copy = array();
    foreach ($node->{$field['field_name']}['en'] as $item) {
      if (in_array($item['fid'], $form_state['values'][$field['field_name']])) {
        $items_to_copy[] = $item;
      }
    }

    // Copy the files to all selected languages.
    foreach ($form_state['values']['spread_files_target_language'] as $lang_code => $value) {
      if ($value) {
        foreach ($items_to_copy as $item_to_copy) {
          $exists = FALSE;
          foreach ($node->{$field['field_name']}[$lang_code] as $item) {
            if ($item_to_copy['fid'] == $item['fid']) {
              $exists = TRUE;
              break;
            }
          }
          if (!$exists) {
            $node->{$field['field_name']}[$lang_code][] = $item_to_copy;
          }
        }
      }
    }
  }

  node_save($node);
}

function osha_lingua_tools_get_country_codes() {
  $exclude_country_codes = variable_get('osha_lingua_tools_exclude_country_codes', []);
  $exclude_country_statuses = variable_get('osha_lingua_tools_exclude_country_status', [3018, 3021]);
  $voc = taxonomy_vocabulary_machine_name_load('country');
  if (empty($voc)) {
    return ;
  }
  $list = [];
  $term_tree = taxonomy_get_tree($voc->vid, 0, NULL, TRUE);
  foreach($term_tree as $term) {
    $iso = $term->field_iso2[LANGUAGE_NONE][0][value];
    if (!$term->field_country_status) {
      continue;
    }
    if (in_array($iso, $exclude_country_codes)) {
      continue;
    }
    if (in_array($term->field_country_status[LANGUAGE_NONE][0]['tid'], $exclude_country_statuses)) {
      continue;
    }
    $list[$iso] = $term->name;
  }
  return $list;
}

function osha_lingua_tools_batch_operation_copy($nid, $settings, &$context) {
  $countries = array_keys($settings['countries']);
  $country_codes = osha_lingua_tools_get_country_codes();
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = count($settings['countries']);
    $context['results']['settings'] = $settings;
    $context['results']['results'] = array();
  }

  $prefix_title = $settings['prefix_title'];
  $suffix_title = $settings['suffix_title'];
  $country_code = $countries[$context['sandbox']['progress']];
  $country = $country_codes[$country_code];

  $node = osha_copy_publication_translation_original($nid, $form_state, $prefix_title, $suffix_title, $country);

  $context['results']['results'][$node->nid] = $node->title;
  $context['sandbox']['progress']++;
  $context['message'] = t('Now processing \'%node\'', array('%node' => $node->title));
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

function osha_lingua_tools_batch_copy_finished($success, $results, $operations) {
  if ($success) {
    $message = t('@count publications successfully copied.', array('@count' => count($results['results'])));
    drupal_set_message($message);
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments',
      array('%error_operation' => $error_operation[0], '@arguments' => print_r($error_operation[1], TRUE)));
    drupal_set_message($message, 'error');
  }
}

function osha_lingua_tools_copy_one_publication_for_each_country($form, &$form_state) {
  $values = $form_state['values'];
  if (!empty($form['#node'])) {
    $values['node'] = $form['#node'];
  }
  $nid = $values['node'];
  $batch = array(
    'operations' => array(
      array('osha_lingua_tools_batch_operation_copy', array($nid, $values)),
    ),
    'finished' => 'osha_lingua_tools_batch_copy_finished',
    'title' => t('Processing Copy Publication Translation Batch'),
    'init_message' => t('Copy Publication Translation Batch is starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Copy Publication Translation Batch has encountered an error.'),
  );
  batch_set($batch);
  batch_process();
}
