<?php

/**
 * Implements hook_menu().
 */
function osha_unpublish_menu() {
  $items = array();
  $items['admin/config/system/osha_unpublish'] = array(
    'title' => 'Auto Archive Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('osha_unpublish_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements Elysia hook_cronapi().
 */
function osha_unpublish_cronapi() {
  return array('osha_unpublish_cron' => array(
    'description' => 'Unpublish content',
    'rule' => '42 0 * * *',
  ));
}

/**
 * Implements hook_cron().
 */
function osha_unpublish_cron() {
  $types = node_type_get_types();
  foreach ($types as $type_name => $type) {
    $interval = variable_get('osha_unpublish_' . $type_name, 0);
    if (!empty($interval)) {
      $time = strtotime('-' . $interval . ' months');
      $date = date('Y-m-d H:i:s', $time);
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $type_name)
        ->propertyCondition('status', NODE_PUBLISHED)
        ->fieldCondition('field_publication_date', 'value', $date, '<');
      $result = $query->execute();
      if (isset($result['node'])) {
        $nids = array_keys($result['node']);
      }
      // Get nodes without publication_date.
      $subquery = db_select('field_data_field_publication_date', 'pd')
        ->fields('pd', array('entity_id'))
        ->condition('pd.bundle', $type_name)
        ->condition('pd.deleted', 0);
      $nids_created = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->condition('n.created', $time, '<')
        ->condition('n.type', $type_name)
        ->condition('n.nid', $subquery, 'NOT IN')
        ->execute()
        ->fetchCol();
      $unpublishing_nids = array_merge($nids, $nids_created);
      if (!empty($unpublishing_nids)) {
        $nodes = node_load_multiple($unpublishing_nids);
        foreach ($nodes as $node) {
          $node->status = 0;
          node_save($node);
        }
      }
    }
  }
}

function osha_unpublish_settings_form($form, &$form_state) {
  $form = array();
  $types = node_type_get_types();
  $info = field_info_field('field_publication_date');
  $form['desc'] = array(
    '#type' => 'markup',
    '#markup' => 'Auto unpublish content by months passed since field_publication_date',
  );
  if (!empty($info['bundles']['node'])) {
    $intervals = array(0, 1, 3, 6, 12, 18, 24);
    foreach ($info['bundles']['node'] as $type_name) {
      $form['osha_unpublish_' . $type_name] = array(
        '#title' => $types[$type_name]->name,
        '#type' => 'select',
        '#options' => drupal_map_assoc($intervals),
        '#default_value' => variable_get('osha_unpublish_' . $type_name, 0),
      );
    }
    $form = system_settings_form($form);
  }

  return $form;
}
