<?php
/**
 * @file
 * osha_dangerous_substances.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function osha_dangerous_substances_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-4S7paT2fc0vb40WhDxH3UVrOr7tv3Fui'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '4S7paT2fc0vb40WhDxH3UVrOr7tv3Fui',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 14,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of provider',
    'visibility' => 1,
  );

  $export['facetapi-6UESvdgGlNWwNAW14Ox480cpaXPvX4bM'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6UESvdgGlNWwNAW14Ox480cpaXPvX4bM',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 13,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of item',
    'visibility' => 1,
  );

  $export['facetapi-Bpod0rRbjpbbVOTZ2lNUYM4vk4Ko9muq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Bpod0rRbjpbbVOTZ2lNUYM4vk4Ko9muq',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 19,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Purpose of the material',
    'visibility' => 1,
  );

  $export['facetapi-C7pGUEytAAJ1U6cAFc9WF8agLRsPLVVw'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'C7pGUEytAAJ1U6cAFc9WF8agLRsPLVVw',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 16,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tasks covered',
    'visibility' => 1,
  );

  $export['facetapi-JCAloFsFwfdccn5MMohljujWHi0XstK2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'JCAloFsFwfdccn5MMohljujWHi0XstK2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 15,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 1,
  );

  $export['facetapi-SP2vjV6LCqa4JeUtyONVT0T5rb6s6UHK'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'SP2vjV6LCqa4JeUtyONVT0T5rb6s6UHK',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 20,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Target group',
    'visibility' => 1,
  );

  $export['facetapi-kpQcK2o2khSmGT6LYyukJc5NO1t2anJ0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'kpQcK2o2khSmGT6LYyukJc5NO1t2anJ0',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 18,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Worker groups covered',
    'visibility' => 1,
  );

  $export['facetapi-p10ryKQWozY46EFH6tpu31b5W8YN9C4N'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'p10ryKQWozY46EFH6tpu31b5W8YN9C4N',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search
themes/dangerous-substances/search/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 17,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Available in languages',
    'visibility' => 1,
  );

  $export['osha_dangerous_substances-block_osha_dangerous_substances'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'block_osha_dangerous_substances',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'osha_dangerous_substances',
    'node_types' => array(),
    'pages' => 'themes/dangerous-substances/search_old
themes/dangerous-substances/search_old/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'before_footer',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  return $export;
}
