<?php
/**
 * @file
 * Code for the Job vacancies feature.
 */

include_once 'osha_job_vacancies.features.inc';

define('OSHA_JOB_VACANCIES_CONTENT_TYPE_JOB_VACANCIES', 'job_vacancies');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_job_vacancies_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create job_vacancies content',
        'edit own job_vacancies content',
        'edit any job_vacancies content',
        'delete own job_vacancies content',
        'delete any job_vacancies content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

function osha_job_vacancies_post_features_revert($component) {
}

/**
 * Implements hook_node_validate().
 *
 * {@inheritdoc}
 */
function osha_job_vacancies_node_validate($node, $form, &$form_state) {
  $values = $form_state['values'];
  if ($node->type == 'job_vacancies' &&
      !empty($values['field_job_vacancies_deadline'][LANGUAGE_NONE][0]['value']) &&
      !empty($values['field_publication_date'][LANGUAGE_NONE][0]['value'])
  ) {
    $deadline_date = strtotime($values['field_job_vacancies_deadline'][LANGUAGE_NONE][0]['value']);
    $publication_date = strtotime($values['field_publication_date'][LANGUAGE_NONE][0]['value']);
    // Assume that all fields use the same timezone handling settings.
    if ($deadline_date < $publication_date) {
      form_set_error('field_job_vacancies_deadline', 'Deadline must be after the publication date');
    }
    if (!empty($values['field_expiration_date'][LANGUAGE_NONE][0]['value'])) {
      $expiration_date = strtotime($values['field_expiration_date'][LANGUAGE_NONE][0]['value']);
      if ($expiration_date < $deadline_date) {
        form_set_error('field_expiration_date', 'Item must expire after the deadline');
      }
    }
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_job_vacancies_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_job_vacancies', 'osha_job_vacancies.translations');
  return osha_job_vacancies_get_translatable_strings();
}
