<?php

/**
 * Implements hook_install().
 */
function osha_wiki_install() {
}

/**
 * MDR-1450 I2-Introduce hint text inside the input fields
 */
function osha_wiki_update_7001() {
  features_revert(array('osha_wiki' => array('field_base', 'field_instance')));
}

/**
 * MDR-4244 remove the old thesaurus.
 */
function osha_wiki_update_7002() {
  $instance = field_info_instance('node','field_thesaurus','wiki_page');
  field_delete_instance($instance);
  features_revert_module('osha_wiki');
}
