<?php
/**
 * @file
 * Code for the osha_thesaurus feature.
 */

include_once 'osha_thesaurus.features.inc';

/**
 * Implements hook_block_info().
 */
function osha_thesaurus_block_info() {
  $blocks = array();
  $blocks['osha_thesaurus_test_block'] = array(
    'info' => t('Thesaurus test block'),
    'status' => 1,
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * {@inheritdoc}
 */
function osha_thesaurus_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'osha_thesaurus_test_block':
      $block['subject'] = '';
      $block['content'] = osha_thesaurus_block_content();
      break;
  }
  return $block;
}

function osha_thesaurus_block_content()
{
	$content = "<p>".t("EU-OSHA’s multilingual thesaurus of occupational safety and health terminology lists words grouped together in a hierarchy. It includes synonyms and antonyms of those words and some definitions.")."</p>";

	return $content;
}

/**
 *
 * When using search_autocomplete module.
 */
function osha_thesaurus_autocomplete_callback($search = '*') {
  if (empty(arg(1)) && !empty($_REQUEST['term'])) {
    $search = $_REQUEST['term'];
  }
  $search = check_plain($search);
  global $language;
  $lang = $language->language;
  $allowed_bundles = array("thesaurus"=>"thesaurus");
  $bundles = node_type_get_types();

  $index = search_api_index_load('thesaurus');
  $server = search_api_server_load('solr_server');
  $connection = new SearchApiSolrConnection($server->options);

  // Build params - group by bundle, 3 rows each.
  $params = array(
    'group' => 'true',
    'group.field' => 'ss_type',
    'group.limit' => 10,
  );
  $params['fq'][] = 'ss_search_api_language:"' . $lang . '"';
  // Add condition for excluded bundles.
  $params['fq'][]='index_id:"thesaurus"';
  // Add searchable fields.
  $fields = $index->getFields();
  $search_fields = array("title_field"=>"title_field");
  foreach ($search_fields as $field) {
    $params['qf'][] = 'tm_' . $field . '^' . $fields[$field]['boost'];
    $params['qf'][] = 'tm_und' . $field . '^' . $fields[$field]['boost'];
    $params['qf'][] = 'tm_' . $lang . '_' . $field . '^' . $fields[$field]['boost'];
  }
  // Make the search.
  $request = $connection->search($search, $params);

  $data = json_decode($request->data);
  $total_groups = count($data->grouped->ss_type->groups);
  $total_items = $data->grouped->ss_type->matches;
  $return = array();

  $showing_categ = 10;
  $showing_items = 10;
  $count_categ = 0;
  $showed_items = 0;
  $showed_categ = 0;
  $total_on_showed_categ = 0;
  $wiki_result = array();
  $total_wiki_results = 0;

  foreach ($data->grouped->ss_type->groups as &$group) {
    $ret = osha_search_autocomplete_add_group($group, $lang, $showing_items, $search);
    $showed_items += $ret['count'];
    $showed_categ += ($ret['count']) ? 1 : 0;
    $total_on_showed_categ += $group->doclist->numFound;
    $return = array_merge($return, $ret['results']);
  }
  print_r(json_encode($return));
  exit;
}

/**
 * Function to check if the user can access the Thesaurus Excel Generation page or not
 */
function osha_thesaurus_excel_generate_access() {
  if (user_access('edit any thesaurus content')) {
    return TRUE;
  }
  return FALSE;
}

/**
* Form to generate the Excel files with the thesaurus files
**/
function osha_thesaurus_excel_generate()
{
  global $language;

  $currentLang = $language;

  $installed = osha_language_list(TRUE);
  // Check if the language argument comes in the URL
  if ($selected = arg(3))
  {
    global $base_root;

    // Check if the directory exists and create it if it doesn't
    $directory = 'public://thesaurus-export/';
    file_prepare_directory($directory, FILE_CREATE_DIRECTORY);

    // Define the destination route for the file
  	$dest = 'public://' . 'thesaurus-export/EU-OSHA_thesaurus_' . $selected . '.xls';  	

    // Call to the export view in order to create the Excel file
  	$file = file_get_contents($base_root . "/" . $selected . "/tools-and-resources/eu-osha-thesaurus/export");
    
    file_unmanaged_save_data($file, $dest, FILE_EXISTS_REPLACE);
  }
  else
  {
    // Add js and css
    $form = array(
      '#attached' => array(
        'js' => array(
          array(
            'data' => drupal_get_path('module', 'osha_thesaurus') . '/js/osha_thesaurus.js',
            'type' => 'file',
            'weight' => 10,
          )
        ),
      ),
    );

    $form['intro']['#markup'] = t('<p>Please select the language version that you want to generate the Thesaurs XLS file, and click on the "Generate Excel" button in the corresponding column.<br>
  Please remember that the Excel is generated using the published content of the thesaurus.</p>');

    $header = [t('Language'), t('Actions'), t('Date of the Excel file')];
    $rows = [];
    foreach ($installed as $code => $lang) {
      $dest = 'public://' . 'thesaurus-export/EU-OSHA_thesaurus_' . $code . '.xls';
      $date = '';
      if (file_exists($dest)) {
        $date = date('d-m-Y', filemtime($dest));
      }
      $rows[] = [
        $lang->name,
        "<a href='javascript:generateExcel(\"".$code."\");'>Generate Excel</a>",
        // l(t('Generate Excel'), 'admin/content/thesaurus-excel-generation/' . $code),
        $date
      ];
    }
    $form['rows']['#markup'] = theme('table', array(
      'header' => $header,
      'rows' => $rows,
    ));
    return $form;
  }
}

/**
 * Implements hook_menu().
 */
function osha_thesaurus_menu() {
  $items = array();
  $items['thesaurus-search-autocomplete/%'] = array(
    'page callback' => 'osha_thesaurus_autocomplete_callback',
    'access callback' => TRUE,
    'page arguments' => array(1),
  );
  $items['thesaurus-search-autocomplete'] = array(
    'page callback' => 'osha_thesaurus_autocomplete_callback',
    'access callback' => TRUE,
  );  
  $items['admin/content/thesaurus-excel-generation'] = array(
    'title' => 'Generate Excel files',
    'page callback' => 'osha_thesaurus_excel_generate',
    'access callback' => 'osha_thesaurus_excel_generate_access',
    // 'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/thesaurus-excel-generation/%'] = array(
    'title' => 'Generate Excel files',
    'page callback' => 'osha_thesaurus_excel_generate',
    'access callback' => 'osha_thesaurus_excel_generate_access',
    'page arguments' => array(1),
    // 'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

