<?php

module_load_include('inc', 'osha_reminders', 'osha_reminders.admin');

/**
 * Implements hook_menu().
 */
function osha_reminders_menu() {
  $items = array();
  $items['admin/config/system/osha_reminders'] = array(
    'title' => 'EU-OSHA Reminders',
    'description' => 'Config information for the module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('osha_reminders_admin_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements Elysia hook_cronapi().
 */
function osha_reminders_cronapi() {
  return array('osha_reminders_cron' => array(
    'description' => 'Send reminders about content not reviewed recently and broken links (run interval overridden in hook!)',
    'rule' => '0 * * * *', // Every hour (Actual date handled in hook_cron)
  ));
}

function osha_reminders_convert_to_time($date) {
  $date['year'] = date('Y');
  $date = $date['year'] . '-' . $date['month'] . '-' . $date['day'];
  $time = strtotime($date);
  return $time;
}

function osha_reminders_allow_run($curr, $last_run, $check_dates) {
  if (date('m-d', $curr) == date('m-d', $last_run)) {
    return FALSE;
  }
  foreach($check_dates as $i => $check_date) {
    if (date('m-d', $curr) == date('m-d', $check_date)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_cron().
 */
function osha_reminders_cron() {
  // Check if to notify PM about their content.
  $last_run = variable_get('osha_reminders_pm_notify_last_run', REQUEST_TIME);
  $pm1 = variable_get('osha_reminders_pm_notify_md1', ['day' => 15,'month' => 1,'year' => date('Y')]);
  $time1 = osha_reminders_convert_to_time($pm1);
  $pm2 = variable_get('osha_reminders_pm_notify_md2', ['day' => 15,'month' => 3,'year' => date('Y')]);
  $time2 = osha_reminders_convert_to_time($pm2);
  $allow_run = osha_reminders_allow_run(REQUEST_TIME, $last_run, [$time1, $time2]);
  if ($allow_run) {
    osha_reminders_notify_pm();
    variable_set('osha_reminders_pm_notify_last_run', REQUEST_TIME);
  }

  // Check if to notify heads about content.
  $heads_last_run = variable_get('osha_reminders_heads_notify_last_run', REQUEST_TIME);
  $head1 = variable_get('osha_reminders_heads_notify_md1', ['day' => 15, 'month' => 3,'year' => date('Y')]);
  $time1 = osha_reminders_convert_to_time($head1);
  $head2 = variable_get('osha_reminders_heads_notify_md2', ['day' => 15, 'month' => 9,'year' => date('Y')]);
  $time2 = osha_reminders_convert_to_time($head2);
  $allow_run = osha_reminders_allow_run(REQUEST_TIME, $heads_last_run, [$time1, $time2]);
  if ($allow_run) {
    osha_reminders_notify_heads();
    variable_set('osha_reminders_heads_notify_last_run', REQUEST_TIME);
  }
}

/**
 * Send notifications to PM about their sections.
 */
function osha_reminders_notify_pm() {
  $users = osha_reminders_get_sections_pm();
  $params = array();
  $module = 'osha_reminders';
  osha_reminders_send_email($users, $params, $module, 'osha_reminders_pm_section');
}

/**
 * Send notifications to Heads about Sections review statuses.
 */
function osha_reminders_notify_heads() {
  $rid = variable_get('osha_reminders_heads_role', 7);
  $users = OshaWorkflowPermissions::getUsersByRole($rid);
  $params = array();
  $module = 'osha_reminders';
  osha_reminders_send_email($users, $params, $module, 'osha_reminders_head_section');
}

/**
 * Get PM users that have a section assigned.
 */
function osha_reminders_get_sections_pm() {
  $pms = db_select('osha_workflow_access_pm', 'owa')
    ->fields('owa')
    ->execute()
    ->fetchAllAssoc('uid');
  return user_load_multiple(array_keys($pms));
}

/**
 * Send bulk emails to a list of users.
 */
function osha_reminders_send_email($users, $params, $module, $key = 'osha_reminders_pm_section') {
  if (empty($users)) {
    drupal_set_message('There are no users to notify about your action. Please report this to system administrator.', 'warning');
    return;
  }
  if (!is_array($users)) {
    $users = array($users);
  }
  foreach ($users as $user) {
    if (OshaWorkflowNotifications::userAllowsEmailNotifications($user)) {
      $params['user'] = $user;
      drupal_mail($module, $key, $user->mail, user_preferred_language($user), $params);
    }
  }
}

/**
 * Implements hook_mail().
 *
 * {@inheritdoc}
 */
function osha_reminders_mail($key, &$message, $params) {
  switch ($key) {
    case 'osha_reminders_pm_section':
      // Get the url for broken links with filtering for pm's assigned sections.
      $sections = osha_workflow_access_get_pm_sections($params['user']->uid);
      $url_broken_links = url('admin/content/linkchecker-broken-links',
        array(
          'query' => array('access_id' => $sections),
          'absolute' => TRUE,
        )
      );
      $sections_terms = taxonomy_term_load_multiple($sections);
      $section_names = [];
      foreach ($sections_terms as $term) {
        $section_names[] = l($term->name, 'admin/config/workbench/access/managers/review/taxonomy/' . $term->tid, array('absolute' => TRUE));
      }
      $content_url = url('admin/content', array(
        'query' => array('access_id' => $sections),
        'absolute' => TRUE,
      ));

      $subject = variable_get('osha_reminder_template_pm_subject', '[OSHA Website] Reminders: Review your Sections');
      $body = variable_get('osha_reminder_template_pm_body',
        'Dear [user:name],<br/>
<br/>
As project manager for [pm_sections], you are kindly invited to review the <a href="[sections_content_url]">content of your section</a>.<br/>
You can check the broken links in <a href="[broken_links_url]">this page</a>.<br/>
Please, remember that the content should be relevant and up to date, and the links should work properly.<br/>
<br/>
Thanks a lot for reviewing your contents.<br/>'
      );

      $body = str_replace('[broken_links_url]', $url_broken_links, $body);
      $body = str_replace('[pm_sections]', implode(', ', $section_names), $body);
      $body = str_replace('[sections_content_url]', $content_url, $body);
      $message['subject'] = token_replace($subject, $params);
      $message['body'][] = token_replace($body, $params);
      break;

    case 'osha_reminders_head_section':
      $subject = variable_get('osha_reminder_template_heads_subject', '[OSHA Website] Reminders: Content Update Status');
      $body = variable_get('osha_reminder_template_heads_body',
        'Dear [user:name],<br/>
<br/>
This is a reminder for you to check content status <a href="[site:url]/admin/config/workbench/access/managers">in this screen</a>.<br/>
You can check the broken links in <a href="[site:url]/admin/content/linkchecker-broken-links">this page</a>.<br/>
<br/>
Thank you,<br/>'
      );
      $message['subject'] = token_replace($subject, $params);
      $message['body'][] = token_replace($body, $params);
      break;
  }
}
