<?php

function osha_publication_install() {
  //osha_publication_add_menu_position_rules();
}

/**
 * Add publication menu position rules
 */
function osha_publication_update_7001() {
  //osha_publication_add_menu_position_rules();
}

/**
 * Add menu position rules for publication content type.
 */
function osha_publication_add_menu_position_rules() {
  if (module_exists('osha') && module_load_include('inc', 'osha', 'osha.utils')) {
    $condition = array('content_type' => array('publication' => 'publication'));
    osha_add_menu_position_rule('Publications Menu Rule', '------ Publications', $condition);
  }
}

/**
 * Removes the redirects ending in /view for nodes.
 */
function osha_publication_update_7002() {
  db_delete('redirect')
    ->condition('source', db_like('%/view'), 'LIKE')
    ->condition('redirect', db_like('node/%'), 'LIKE')
    ->execute();
}

/**
 * Add field_relevant_for and populate the taxonomy.
 */
function osha_publication_update_7003() {
    // feature revert, to have the new taxonomy and term reference field
    features_revert_module('osha_publication');
    $vocabulary = taxonomy_vocabulary_machine_name_load('relevant_for');
    // create terms
    $terms = array('Employers', 'HR managers', 'OSH professionals', 'Policy makers', 'Researchers', 'Workers');
    foreach ($terms as $term_name) {
      $term = new stdClass();
      $term->vid = $vocabulary->vid;
      $term->name = $term->name_field['en'][0]['value'] = $term_name; 
      $term->language = 'en';
      taxonomy_term_save($term);
    }
}

/**
 * Revert osha_publication.
 */
function osha_publication_update_7004() {
  features_revert(array('osha_publication' => array('fe_block_settings', 'views_view')));
}

/**
 * Revert osha_publication.
 */
function osha_publication_update_7005() {
  features_revert_module('osha_publication');
}

/**
 * Fix some publications thumbnails.
 */
function osha_publication_update_7006() {
  global $base_url;
  $aliases = array(
    '/tools-and-publications/publications/reports/economic_incentives_TE3109255ENC',
    '/tools-and-publications/publications/reports/105',
    '/tools-and-publications/publications/reports/mainstreaming_osh_business',
    '/tools-and-publications/publications/reports/TERO09009ENC',
    '/tools-and-publications/publications/reports/mainstream_osh_university_education',
    '/tools-and-publications/publications/reports/TE7809894ENC',
    '/tools-and-publications/publications/reports/TEWE09006ENC',
    '/tools-and-publications/publications/reports/TEWE09001ENC',
    '/tools-and-publications/publications/reports/548OELs',
    '/tools-and-publications/publications/reports/TE3008390ENC_chemical_risks',
    '/tools-and-publications/publications/reports/8108322_vibration_exposure',
    '/tools-and-publications/publications/reports/TE7007049ENC_skin_diseases',
    '/tools-and-publications/publications/reports/en_TE8107132ENC.pdf',
    '/tools-and-publications/publications/reports/7807118',
    '/tools-and-publications/publications/corporate/2006',
    '/tools-and-publications/publications/corporate/brochure_2007',
    '/tools-and-publications/publications/magazine/9',
    '/tools-and-publications/publications/corporate/2005',
    '/tools-and-publications/publications/corporate/2005full',
    '/tools-and-publications/publications/reports/6805648',
    '/tools-and-publications/publications/reports/6805535',
    '/tools-and-publications/publications/magazine/8',
    '/tools-and-publications/publications/corporate/20050929',
    '/tools-and-publications/publications/corporate/2004',
    '/tools-and-publications/publications/corporate/2004full',
    '/tools-and-publications/publications/reports/314',
    '/tools-and-publications/publications/reports/210',
    '/tools-and-publications/publications/magazine/7',
    '/tools-and-publications/publications/reports/313',
    '/tools-and-publications/publications/reports/107',
    '/tools-and-publications/publications/corporate/2003full',
    '/tools-and-publications/publications/corporate/2003',
    '/tools-and-publications/publications/reports/312',
    '/tools-and-publications/publications/reports/209',
    '/tools-and-publications/publications/reports/406',
    '/tools-and-publications/publications/corporate/2002',
    '/tools-and-publications/publications/magazine/6',
    '/tools-and-publications/publications/reports/105',
    '/tools-and-publications/publications/corporate/2001',
    '/tools-and-publications/publications/magazine/5',
    '/tools-and-publications/publications/magazine/4',
    '/tools-and-publications/publications/reports/103',
    '/tools-and-publications/publications/reports/102',
    '/tools-and-publications/publications/reports/304',
    '/tools-and-publications/publications/magazine/3',
    '/tools-and-publications/publications/corporate/2013full',
    '/tools-and-publications/publications/corporate/2011full',
    '/tools-and-publications/publications/corporate/ar_summary_2011',
    '/tools-and-publications/publications/reports/transport-sector_TERO10001ENC',
    '/tools-and-publications/publications/reports/safe-maintenance-TEWE10003ENC',
    '/tools-and-publications/publications/reports/TE-81-08-478-EN-C_OSH_in_figures_stress_at_work',
    '/tools-and-publications/publications/osh-figures-stress-work-facts-and-figures',
    '/publications/reports/305',
    '/publications/reports/401',
    '/publications/magazine/2',
    '/publications/reports/201',
    '/tools-and-publications/publications/corporate/1998',
  );

  $images_dir = 'public://publications/cover_images';
  if (!file_prepare_directory($images_dir)) {
    throw new DrupalUpdateException('Could not prepare directory ' . $images_dir);
  }

  foreach ($aliases as $alias) {
    $path = path_load(array('alias' => substr($alias, 1)));
    if (!empty($path)) {
      $nid = str_replace('node/', '', $path['source']);
      $node = node_load($nid);
      if (!empty($node->field_cover_image)) {
        foreach ($node->field_cover_image as $lng => $cover) {
          $file = $node->field_file[$lng][0];
          $file_path = file_create_url($file['uri']);
          $file_url = str_replace($base_url, 'https://osha.europa.eu', $file_path);

          $convertor_url = 'http://osha.edw.ro/oshathumbnailgenerator?url=' . $file_url;
          $ch = curl_init($convertor_url);
          $image_path = $images_dir . '/' .$node->nid . '.jpg';
          if($ch){
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            $data = curl_exec($ch);
            if ($data !== FALSE && imagecreatefromstring($data) !== FALSE) {
              $new_cover = file_save_data($data, $image_path, FILE_EXISTS_RENAME);
            }
            else {
              throw new DrupalUpdateException(strtr('File @path could not be converted with @convertor', array('@path' => $images_dir, '@convertor' => $convertor_url)));
            }
            curl_close($ch);
          }
          if (!empty($new_cover)) {
            $new_cover->status = 1;
            $new_cover->display = 1;
            $node->field_cover_image[$lng][0] = (array) $new_cover;
          }
        }
        node_save($node);
      }
    }
  }
}

/**
 * Fix some publications thumbnails (broken) that already exists.
 */
function osha_publication_update_7007() {
  global $base_url;
  $aliases = array(
    '/tools-and-publications/publications/reports/201',
    '/tools-and-publications/publications/reports/esener_workers-involvement',
    '/tools-and-publications/publications/reports/TE7809894ENC',
    '/tools-and-publications/publications/reports/305',
    '/tools-and-publications/publications/reports/401',
    '/tools-and-publications/publications/magazine/2',
    '/tools-and-publications/publications/reports/303',
  );

  $images_dir = 'public://publications/cover_images';
  if (!file_prepare_directory($images_dir)) {
    throw new DrupalUpdateException('Could not prepare directory ' . $images_dir);
  }

  foreach ($aliases as $alias) {
    $path = path_load(array('alias' => substr($alias, 1)));
    if (!empty($path)) {
      $nid = str_replace('node/', '', $path['source']);
      $node = node_load($nid);
      if (!empty($node->field_cover_image)) {
        foreach ($node->field_cover_image as $lng => $cover) {
          $file = $node->field_file[$lng][0];
          $file_path = file_create_url($file['uri']);
          $file_url = str_replace($base_url, 'https://osha.europa.eu', $file_path);

          $convertor_url = 'http://osha.edw.ro/oshathumbnailgenerator?url=' . $file_url;
          $ch = curl_init($convertor_url);
          $image_path = $images_dir . '/' .$node->nid . '.jpg';
          if ($ch){
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            $data = curl_exec($ch);
            if ($data !== FALSE && imagecreatefromstring($data) !== FALSE) {
              $new_cover = file_save_data($data, $image_path, FILE_EXISTS_RENAME);
            }
            else {
              throw new DrupalUpdateException(strtr('File @path could not be converted with @convertor', array('@path' => $images_dir, '@convertor' => $convertor_url)));
            }
            curl_close($ch);
          }
          if (!empty($new_cover)) {
            $new_cover->status = 1;
            $new_cover->display = 1;
            $node->field_cover_image[$lng][0] = (array) $new_cover;
          }
        }
        node_save($node);
      }
    }
  }
}

/**
 * Try to re-generate covers for publications that are missing covers.
 */
function osha_publication_update_7008() {
  global $base_url;
  $subquery = db_select('field_data_field_cover_image', 'ci')
    ->fields('ci', array('entity_id'))
    ->condition('bundle', 'publication')
    ->distinct('entity_id');
  $subquery2 = db_select('field_data_field_file', 'cf')
    ->fields('cf', array('entity_id'))
    ->condition('bundle', 'publication')
    ->distinct('entity_id');
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'publication')
    ->condition('nid', $subquery, 'NOT IN')
    ->condition('nid', $subquery2, 'IN');
  $result =$query->execute()->fetchCol();

  $images_dir = 'public://publications/cover_images';
  if (!file_prepare_directory($images_dir)) {
    throw new DrupalUpdateException('Could not prepare directory ' . $images_dir);
  }

  foreach ($result as $nid) {
    $node = node_load($nid);
    foreach (array_keys($node->field_file) as $lng) {
      $file = $node->field_file[$lng][0];
      $file_path = file_create_url($file['uri']);
      $file_url = str_replace($base_url, 'https://osha.europa.eu', $file_path);
      $convertor_url = 'http://osha.edw.ro/oshathumbnailgenerator?url=' . $file_url;
      $ch = curl_init($convertor_url);
      $image_path = $images_dir . '/' .$node->nid . '.jpg';
      if($ch){
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        $data = curl_exec($ch);
        if ($data !== FALSE && imagecreatefromstring($data) !== FALSE) {
          $new_cover = file_save_data($data, $image_path, FILE_EXISTS_RENAME);
        }
        else {
          drupal_set_message(strtr('File @path could not be converted with @convertor', array('@path' => $file_path, '@convertor' => $convertor_url)), 'warning');
        }
        curl_close($ch);
      }
      if (!empty($new_cover)) {
        $new_cover->status = 1;
        $new_cover->display = 1;
        $node->field_cover_image[$lng][0] = (array) $new_cover;
      }
    }
    node_save($node);
  }
}


/**
 * MDR-1012 - Features revert: Added Priority areas field to publications.
 */
function osha_publication_update_7009() {
  features_revert_module('osha_publication');
}

/**
 * MDR-1450 I2-Introduce hint text inside the input fields
 */
function osha_publication_update_7010() {
  features_revert(array('osha_publication' => array('field_base', 'field_instance')));
}

/**
 * MDR-2055 Publications carrorusel does not appear.
 */
function osha_publication_update_7011() {
  features_revert(array('osha_publication' => array('views_view')));
}

/**
 * MDR-2093 NCW: add pictures copyright.
 */
function osha_publication_update_7012() {
  features_revert(array('osha_publication' => array('field_instance')));
}

/**
 * MDR-2568 change the links to the publications office.
 */
function osha_publication_update_7013() {
  features_revert(array('osha_publication' => array('field_instance')));
}

/**
 * MDR-2568 change the links to the publications office.
 */
function osha_publication_update_7014() {
  features_revert(array('osha_publication' => array('field_base', 'field_instance')));
  $nids = db_select('field_data_field_publication_bookshop_id', 'pb')
    ->fields('pb', array('entity_id'))
    ->distinct()
    ->condition('field_publication_bookshop_id_value', '', '!=')
    ->execute()
    ->fetchCol();
  foreach ($nids as $nid) {
    $node = node_load($nid);
    if ($node->field_publication_bookshop_id) {
      foreach ($node->field_publication_bookshop_id as $lang => $value) {
        if (!empty($value[0]['value'])) {
          $node->field_banner_publications_office[$lang][0]['value'] = '1';
        }
      }
      node_save($node);
    }
  }
}

/**
 * MDR-2735 create main publication type taxonomy.
 */
function osha_publication_update_7015() {
  osha_publication_types_create_new_terms();
}

/**
 * MDR-2735 create main publication type taxonomy.
 */
function osha_publication_update_7016() {
  osha_publication_tags_assign_parents();
}

/**
 * MDR-2736 create main publication type taxonomy.
 */
function osha_publication_update_7017() {
  osha_publication_tags_create_new_terms();
}

/**
 * MDR-2736 create main publication type taxonomy.
 */
function osha_publication_update_7018() {
  osha_publication_tags_assign_parents();
}

function osha_publication_types_create_new_terms() {
  $new_terms = 'Case studies
Corporate publications
Discussion papers
European Guides
Info sheets
Promotional Material
Reports
Training resources';
  $new_terms = explode("\n", $new_terms);
  $name = 'publication_types';
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $tree = taxonomy_get_tree($vocabulary->vid);
  foreach ($tree as $i => $term) {
    $tags_map[$term->name] = $term->tid;
  }
  foreach ($new_terms as $new_term) {
    $term_names = [];
    if (!empty($tags_map[$new_term])) {
      $tid = $tags_map[$new_term];
      $term = taxonomy_term_load($tid);
      $term_names = $term->name_field;
      unset($term_names['en']);
    }
    $term = new stdClass();
    $term->name = $term->name_field['en'][0]['value'] = $new_term;
    $term->vid = $vocabulary->vid;
    $term->language = 'en';
    taxonomy_term_save($term);
    // Setting Translations.
    $translation_handler = entity_translation_get_handler('taxonomy_term', $term);
    $term->translations = $translation_handler->getTranslations();
    foreach ($term_names as $lang => $name) {
      if (!isset($term->translations->data[$lang])) {
        $translation_handler->setTranslation(array(
          'translate' => 0,
          'status' => 1,
          'uid' => 1,
          'language' => $lang,
          'source' => 'en',
        ));
      }
      $term->name_field[$lang][0]['value'] = $name;
    }
    taxonomy_term_save($term);
  }
}

function osha_publication_types_assign_parents() {
  $new_tree = 'Case studies
  Case studies
Corporate publications
  Annual reports and other corporate publications
  Evaluation reports
  Corporate strategies and programming documents
Discussion papers
  Discussion papers
European Guides
  European Guides
Info sheets
  E-facts
  Factsheets
  Info sheets
Promotional Material
  Promotional Material
Reports
  Reports
  Literature reviews
Training resources
  Training resources';
  $new_tree = explode("\n", $new_tree);
  $name = 'publication_types';
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $query = db_select('taxonomy_term_data', 't')->fields('h', array('tid', 'parent'));
  $query->join('taxonomy_term_hierarchy', 'h', ' t.tid = h.tid');
  $query->condition('t.vid', $vocabulary->vid)
    ->orderBy('t.weight')
    ->orderBy('t.name');
  $tids = $query->execute()->fetchAll();
  foreach ($tids as $term) {
    if ($term->parent == $term->tid) {
      $term = taxonomy_term_load($term->tid);
      $term->parent = [];
      taxonomy_term_save($term);
    }
  }
  $tree = taxonomy_get_tree($vocabulary->vid);

  $tags_map = [];
  foreach ($tree as $i => $term) {
    $name = trim($term->name);
    if (empty($tags_map[$name])) {
      $tags_map[$name] = [$term->tid];
    }
    else {
      $tags_map[$name][] = $term->tid;
    }
  }
  $main = '';
  foreach ($new_tree as $row) {
    $name = trim($row);
    if (strlen($row) == strlen($name)) {
      $main = trim($row);
    }
    elseif (!empty($tags_map[$name])) {
      $tids = $tags_map[$name];
      $min_tid = min($tids);
      $term = taxonomy_term_load($min_tid);
      $tids = $tags_map[$main];
      $max_tid = max($tids);
      if ($max_tid != $min_tid) {
        $term->parent = $max_tid;
        taxonomy_term_save($term);
      }
    }
  }
}

function osha_publication_tags_assign_parents() {
  $new_tree = 'Accident prevention
  Accident prevention
Ageing and OSH
  Ageing and OSH
Agriculture and forestry
  Agriculture
Campaigns
  Campaign 2018-2019
Corporate
  Corporate
  Corporate strategies and work programmes
Dangerous substances
  Biological agents
  Carcinogens
  Dangerous substances
Digitalisation
  ICT/digitalisation
Education
  Mainstreaming OSH into education
Emerging risks
  Emerging risks
ESENER
  ESENER
Good OSH is good for business
  Good OSH is good for business
Green jobs
  Green jobs
Health Care
  Health Care
HORECA
  HORECA
Leadership and worker participation
  Leadership
  Worker Participation
Maintenance
  Maintenance
Microenterprises
  Microenterprises
Musculoskeletal disorders
  Musculoskeletal disorders
Nanomaterials
  Nanomaterials
Noise
  Noise
OiRA
  OiRA
OSH and young people
  OSH and young people
Psychosocial risks and stress
  Psychosocial risks and stress
Risk assessment
  Risk assessment
Transport
  Road Transport
Women and OSH
  Women and OSH
Work-related diseases
  Alert and sentinel systems
  Rehabilitation
  Work related diseases
  Work-related cancer';
  $new_tree = explode("\n", $new_tree);
  $name = 'tags';
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $tree = taxonomy_get_tree($vocabulary->vid);

  $tags_map = [];
  foreach ($tree as $i => $term) {
    $name = trim($term->name);
    if (empty($tags_map[$name])) {
      $tags_map[$name] = [$term->tid];
    }
    else {
      $tags_map[$name][] = $term->tid;
    }
  }
  $main = '';
  foreach ($new_tree as $row) {
    $name = trim($row);
    if (strlen($row) == strlen($name)) {
      $main = trim($row);
    }
    elseif (!empty($tags_map[$name])) {
      $tids = $tags_map[$name];
      $min_tid = min($tids);
      $term = taxonomy_term_load($min_tid);
      if (!empty($tags_map[$main])) {
        $tids = $tags_map[$main];
        $max_tid = max($tids);
        if ($max_tid != $min_tid) {
          $term->parent = $max_tid;
          taxonomy_term_save($term);
        }
      }
      else {
        watchdog('osha_publication', 'term ' . $main . ' not found!', WATCHDOG_ALERT);
      }
    }
    else {
      watchdog('osha_publication', 'term ' . $name . ' not found!', WATCHDOG_ALERT);
    }
  }
}

function osha_publication_tags_create_new_terms() {
  $new_terms = 'Accident prevention
Ageing and OSH
Agriculture and forestry
Campaigns
Corporate
Dangerous substances
Digitalisation
Education
Emerging risks
ESENER
Good OSH is good for business
Green jobs
Health Care
HORECA
Leadership and worker participation
Maintenance
Microenterprises
Musculoskeletal disorders
Nanomaterials
Noise
OiRA
OSH and young people
Psychosocial risks and stress
Risk assessment
Transport
Women and OSH
Work-related diseases';
  $new_terms = explode("\n", $new_terms);
  $name = 'tags';
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $query = db_select('taxonomy_term_data', 't')->fields('h', array('tid', 'parent'));
  $query->join('taxonomy_term_hierarchy', 'h', ' t.tid = h.tid');
  $query->condition('t.vid', $vocabulary->vid)
    ->orderBy('t.weight')
    ->orderBy('t.name');
  $tids = $query->execute()->fetchAll();
  foreach ($tids as $term) {
    if ($term->parent == $term->tid) {
      $term = taxonomy_term_load($term->tid);
      $term->parent = [];
      taxonomy_term_save($term);
    }
  }
  $tree = taxonomy_get_tree($vocabulary->vid);
  foreach ($tree as $i => $term) {
    $tags_map[$term->name] = $term->tid;
  }
  foreach ($new_terms as $new_term) {
    $term_names = [];
    if (!empty($tags_map[$new_term])) {
      $tid = $tags_map[$new_term];
      $term = taxonomy_term_load($tid);
      $term_names = $term->name_field;
      unset($term_names['en']);
    }
    $term = new stdClass();
    $term->name = $term->name_field['en'][0]['value'] = $new_term;
    $term->vid = $vocabulary->vid;
    $term->language = 'en';
    taxonomy_term_save($term);
    // Setting Translations.
    $translation_handler = entity_translation_get_handler('taxonomy_term', $term);
    $term->translations = $translation_handler->getTranslations();
    foreach ($term_names as $lang => $name) {
      if (!isset($term->translations->data[$lang])) {
        $translation_handler->setTranslation(array(
          'translate' => 0,
          'status' => 1,
          'uid' => 1,
          'language' => $lang,
          'source' => 'en',
        ));
      }
      $term->name_field[$lang][0]['value'] = $name;
    }
    taxonomy_term_save($term);
  }
}

/**
 * MDR-2842 NCW - Revamp - Publications list and detail - Development.
 */
function osha_publication_update_7019() {
  features_revert_module('osha_publication');
}

function osha_publication_update_7020() {
  // Left menu block.
  db_update('block')
    ->fields(['pages' => 'node/5445
themes/dangerous-substances/practical-tools-dangerous-substances
photo-gallery
tools-and-publications
tools-and-publications/publications
tools-and-publications/publications/*'])
    ->condition('bid', 151)
    ->execute();

  // Clear filter.
  db_update('block')
    ->fields(['pages' => 'search/*
tools-and-publications/seminars
legislation/directives/*
safety-and-health-legislation/european-directives
node/2544
legislation/guidelines/*
themes/dangerous-substances/search
themes/dangerous-substances/search/*
themes/musculoskeletal-disorders/search'])
    ->condition('bid', 947)
    ->execute();

  // Rss block
  db_update('block')
    ->fields(['region' => -1])
    ->condition('bid', 939)
    ->execute();
}

function osha_publication_update_7021() {
  features_revert_module('osha_wiki');
  features_revert_module('osha_resources');
  features_revert_module('osha_infographics');
  features_revert_module('osha_publication');

}
