<?php

function osha_news_update_7001() {
  features_revert_module('osha_news');
}

/**
 * MDR-1450 I2-Introduce hint text inside the input fields.
 */
function osha_news_update_7002() {
  features_revert(array('osha_news' => array('field_base', 'field_instance')));
}

/**
 * MDR-2009 Back end - Events field - Tagging functionality.
 */
function osha_news_update_7003() {
  features_revert(array('osha_news' => array('field_base', 'field_instance')));
}
