<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'osha_news.features.inc';

define('OSHA_NEWS_CONTENT_TYPE_NEWS', 'news');
define('OSHA_WORKFLOW_ROLE_NEWS_EDITOR', 'News Editor');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 * {@codeCoverageIgnore}
 */
function osha_news_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create news content',
        'edit own news content',
        'edit any news content',
        'delete own news content',
        'delete any news content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_news_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_news', 'osha_news.translations');
  return osha_news_get_translatable_strings();
}

/*
 * Implements hook_node_element_options_alter.
 */
function osha_news_workbench_access_node_element_options_alter(&$options, $form) {
  global $user;
  $is_news_editor = OshaWorkflowPermissions::userHasRole(OSHA_WORKFLOW_ROLE_NEWS_EDITOR, $user);
  if (!$is_news_editor) {
    return;
  }
  if (!in_array($form['#form_id'], ['news_node_form', 'highlight_node_form', 'press_release_node_form'])) {
    return;
  }
  $options = osha_news_workbench_access_options();
}

/*
 * Implements hook_node_element_alter.
 */
function osha_news_workbench_access_node_element_alter(&$element, $form_state) {
  global $user;
  $is_news_editor = OshaWorkflowPermissions::userHasRole(OSHA_WORKFLOW_ROLE_NEWS_EDITOR, $user);
  if (!$is_news_editor) {
    return;
  }
  $node = menu_get_object();
  if ($node) {
    $type = $node->type;
  }
  else {
    $type = arg(2);
  }
  if (!in_array($type, ['news', 'highlight', 'press_release', 'press-release'])) {
    return;
  }
  $element['#type'] = 'select';
  $element['#options'] = osha_news_workbench_access_options();
}

/**
 * Provides all sections.
 */
function osha_news_workbench_access_options() {
  // Prepare the form element.
  $active = workbench_access_get_active_tree();
  if (empty($active['active'])) {
    drupal_set_message(workbench_access_sections_needed_message(), 'warning');
    return;
  }
  $options = array();
  $options[NULL] = t('- Select a value -');
  $options['section'] = t(' Section');
  // Get the user options.
  $active_tree = workbench_access_get_active_tree();
  foreach ($active_tree['active'] as $active) {
    $access_id = $active['access_id'];
    if ($access_id == 'section') {
      continue;
    }
    $options[$access_id] = '- ' . $active_tree['tree'][$access_id]['name'];
  }
  return $options;
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function osha_news_form_views_exposed_form_alter(&$form, &$form_state) {
  global $user;
  $is_news_editor = OshaWorkflowPermissions::userHasRole(OSHA_WORKFLOW_ROLE_NEWS_EDITOR, $user);
  if ($is_news_editor && $form['#id'] == 'views-exposed-form-administration-content-main-page') {
    $form['access_id']['#options'] = osha_news_workbench_access_options();
  }
}

/**
 * Implements hook_form_alter().
 */
function osha_news_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if (!in_array($form_id, [
    'news_node_form', 'highlight_node_form', 'press_release_node_form',
  ])) {
    return;
  }
  $is_news_editor = OshaWorkflowPermissions::userHasRole(OSHA_WORKFLOW_ROLE_NEWS_EDITOR, $user);
  if (!$is_news_editor) {
    return;
  }
  if (
    !empty($form['workbench_access']['workbench_access']['#options']) &&
    count($form['workbench_access']['workbench_access']['#options']) == 1
  ) {
    osha_news_workbench_access_node_element_alter($form['workbench_access']['workbench_access'], $form_state);
  }
  // Only for NEWS EDITOR role and news, highlight and press release node pages.
  $form['#after_build'][] = 'osha_news_workbench_access_remove_after_build';
}

function osha_news_workbench_access_remove_after_build($form, $form_state) {
  unset($form['workbench_access']['message']);
  if (count($form['workbench_access']['workbench_access']['#options']) == 1) {
    osha_news_workbench_access_node_element_alter($form['workbench_access']['workbench_access'], $form_state);
  }
  return $form;
}

/**
 * Implements workaround hook_workbench_access_exceptions().
 */
function osha_news_workbench_access_exceptions_alter(&$exception, $op, $type) {
  if (!in_array($type, ['news', 'highlight', 'press_release'])) {
    return;
  }
  $exception = TRUE;
}
