<?php

/**
 * Implements hook_install().
 */
function osh_image_gallery_install() {
  osh_image_gallery_update_7001();
}

/**
 * Set module weight larger than views'.
 */
function osh_image_gallery_update_7001() {
  db_update('system')
    ->fields(array('weight' => 11))
    ->condition('name', 'osh_image_gallery')
    ->execute();
}

/**
 * MDR-4244 remove the old thesaurus.
 */
function osh_image_gallery_update_7002() {
  features_revert_module('osh_image_gallery');
}
