<?php
/**
 * @file
 * Code for the Infographics feature.
 */

include_once 'osha_infographics.features.inc';

define('OSHA_INFOGRAPHIC_CONTENT_TYPE_INFOGRAPHIC', 'infographic');

/**
 * Implements hook_views_pre_render().
 * @param $view
 */
function osha_infographics_views_pre_render(&$view){
  if ($view->name == 'infographic' && $view->current_display == 'block_2') {
    $view->attachment_before = l(t('All topics'), current_path());
  }elseif ($view->name == 'infographic' && $view->current_display == 'block_1'){
    foreach ($view->result as $result){
      if(isset($result->field_field_image[0]['rendered']['#item'])){
        $result->field_field_image[0]['rendered']['#item']['alt'] = $result->field_title_field[0]['rendered']['#markup'];
        $result->field_field_image[0]['rendered']['#item']['title'] = $result->field_title_field[0]['rendered']['#markup'];
      }
      if(isset($result->field_field_thumbnail[0]['rendered']['#item'])){
        $result->field_field_thumbnail[0]['rendered']['#item']['alt'] = $result->field_title_field[0]['rendered']['#markup'];
        $result->field_field_thumbnail[0]['rendered']['#item']['title'] = $result->field_title_field[0]['rendered']['#markup'];
      }
    }
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_infographics_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_infographics', 'osha_infographics.translations');
  return osha_infographics_get_translatable_strings();
}

/**
 * Implements hook_field_formatter_info().
 */
function osha_infographics_field_formatter_info() {
  $info = array(
    'multilanguage_file' => array(
      'label' => t('Multilanguage File'),
      'field types' => array('file'),
      'description' => t('Download file in: EN, BG ...'),
    ),
    'multilanguage_image' => array(
      'label' => t('Multilanguage Image'),
      'field types' => array('image'),
      'description' => t('Download image in EN, BG ...'),
    ),
    'infographics_title' => array(
      'label' => t('Infographics Title'),
      'field types' => array('text'),
      'settings' => array('title_style' => '', 'title_link' => '', 'title_class' => ''),
    ),
    'external_website_url' => array(
      'label' => t('External website url'),
      'field types' => array('link_field'),
      'description' => t('External website url'),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function osha_infographics_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'external_website_url':
      foreach ($items as $delta => $item) {
        $link_options = $item;
        unset($link_options['title']);
        unset($link_options['url']);
        $link_options['attributes']['target'] = '_blank';
        $markup = "<span class='label_multilang_file'>" . t('Website') . " </span>";
        $markup .= $item['url'] ? l($item['url'], $item['url'], $link_options) : '';
        $element[$delta]['#markup'] = $markup;
      }
      break;

    case 'multilanguage_file':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_infographics_multilanguage_file_format',
          '#entity' => $entity,
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;

    case 'multilanguage_image':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_infographics_multilanguage_image_format',
          '#entity' => $entity,
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;

    case 'infographics_title':
      $settings = $display['settings'];
      $output = '';
      if (isset($items[0]['safe_value'])) {
        $output = $items[0]['safe_value'];
      }
      elseif (isset($items[0]['value'])) {
        $output = _text_sanitize($instance, $langcode, $items[0], 'value');
      }
      $element = array();

      if (!empty($output)) {
        if ($settings['title_link'] == 'content') {
          $uri = entity_uri($entity_type, $entity);
          $options = array('html' => TRUE);
          if (!empty($uri['options'])) {
            $options = array_merge($options, $uri['options']);
          }
          $output = l($output, $uri['path'], $options);
        }

        $wrap_tag = empty($settings['title_style']) ? '_none' : $settings['title_style'];

        if ($wrap_tag != '_none') {
          $variables = array(
            'element' => array(
              '#tag' => $wrap_tag,
              '#value' => $output,
            ),
          );

          if (!empty($settings['title_class'])) {
            $variables['element']['#attributes'] = array('class' => $settings['title_class']);
          }

          $output = theme('html_tag', $variables);
        }

        // If the content is archived, add a label for it.
        if (!empty($output)) {
          if (!empty($entity->field_archived[LANGUAGE_NONE][0]['value'])) {
            $output .= '<span class="title-archived">' . t('Archived') . '</span>';
          }
        }

        $element = array(
          array(
            '#markup' => $output,
          ),
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function osha_infographics_theme() {
  return array(
    'osha_infographics_multilanguage_file_format' => array(
      'variables' => array('entity' => NULL, 'file' => NULL, 'delta' => NULL),
    ),
    'osha_infographics_multilanguage_image_format' => array(
      'variables' => array('entity' => NULL, 'file' => NULL, 'delta' => NULL),
    ),
  );
}

/*
* Formats multilanguage file for download
*/
function theme_osha_infographics_multilanguage_file_format($element) {
  $file = (object) $element['file'];
  $entity = (object) $element['entity'];
  $icon_directory = drupal_get_path('theme', 'osha_frontend') . '/images/file_icons';

  global $language;
  $file = isset($entity->field_file[$language->language][0])
    ? $entity->field_file[$language->language][0]
    : $entity->field_file['en'][0];
  $output = "<span class='label_multilang_file'>Download</span>";
  $output .= theme_file_icon(
    array(
      "file" => file_load($file['fid']),
      "icon_directory" => $icon_directory,
  )
  );
  $output .= "<span class='label_multilang_file'>in:</span>";

  foreach ($entity->field_file as $lang => $object) {
    $output .=  '<a href="' . file_create_url($object[0]['uri']) . '" target="_blank">' . strtoupper($lang) . '</a> | ';
  }
  $output = substr($output, 0, -3);
  return $output;
}

/*
* Formats multilanguage image
*/
function theme_osha_infographics_multilanguage_image_format($element) {
  $file = (object) $element['file'];
  $entity = (object) $element['entity'];
  $icon_directory = drupal_get_path('theme', 'osha_frontend') . '/images/file_icons';

  global $language;
  $file = isset($entity->field_image[$language->language][0])
    ? $entity->field_image[$language->language][0]
    : $entity->field_image['en'][0];
  $output = "<span class='label_multilang_file'>Open</span>";
  $output .= theme_file_icon(
    array(
      "file" => file_load($file['fid']),
      "icon_directory" => $icon_directory,
    ));
  $output .= "<span class='label_multilang_file'>in:</span>";

  foreach ($entity->field_image as $lang => $object) {
    $output .=  '<a href="' . file_create_url($object[0]['uri']) . '" target="_blank">' . strtoupper($lang) . '</a> | ';
  }
  $output = substr($output, 0, -3);
  return $output;
}

/**
 * Implements hook_node_view.
 */
function osha_infographics_node_view_alter(&$build){
  osha_thumbnail_alt_title($build, 'infographic', 'field_thumbnail', 'image');
}

