<?php
/**
 * @file
 * osha_musculoskeletal_disorders.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function osha_musculoskeletal_disorders_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-6ae8QxYdYzUdNtuyskwnVLFp1C3c3SKc'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6ae8QxYdYzUdNtuyskwnVLFp1C3c3SKc',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 27,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Target audience',
    'visibility' => 0,
  );

  $export['facetapi-7GUUvKdxSHbi7d3J11no3hs6D91nbAaU'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7GUUvKdxSHbi7d3J11no3hs6D91nbAaU',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/musculoskeletal-disorders/search',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 32,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Year of publication',
    'visibility' => 1,
  );

  $export['facetapi-AMQfwIHcNdQDSF9AEZVTi261h6qnWPbY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'AMQfwIHcNdQDSF9AEZVTi261h6qnWPbY',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 12,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Language',
    'visibility' => 0,
  );

  $export['facetapi-Gx1DiOl0RNnHVOJ9ULsYdd0t0DbWyVkt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Gx1DiOl0RNnHVOJ9ULsYdd0t0DbWyVkt',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 15,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-Jss4AyiHW37eIf7PwS3oZd25UW1k5ohE'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Jss4AyiHW37eIf7PwS3oZd25UW1k5ohE',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-N3Ptct1LxZ8Va1wrf3o1QbJeoWgHAx4r'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'N3Ptct1LxZ8Va1wrf3o1QbJeoWgHAx4r',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 9,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 0,
  );

  $export['facetapi-Q6zCxqVERYmcnSH45aIyHkuhqrYAqzQP'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Q6zCxqVERYmcnSH45aIyHkuhqrYAqzQP',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 19,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Sector',
    'visibility' => 0,
  );

  $export['facetapi-WAJhe6O2ewe97ytsjQFMJK5axqJTDAf4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'WAJhe6O2ewe97ytsjQFMJK5axqJTDAf4',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/musculoskeletal-disorders/search',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 7,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Recommended for EU-OSHA pictogram guide',
    'visibility' => 1,
  );

  $export['facetapi-arJeDweSgVLVhj7yJFOc17uGLezW8lYX'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'arJeDweSgVLVhj7yJFOc17uGLezW8lYX',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 18,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Priority area',
    'visibility' => 0,
  );

  $export['facetapi-hq5EnxYBzk4f2gHVpsYddOPXAXEGYe7E'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'hq5EnxYBzk4f2gHVpsYddOPXAXEGYe7E',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'themes/musculoskeletal-disorders/search',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 6,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Nominated by FOP',
    'visibility' => 1,
  );

  $export['facetapi-i5ydMupPxxWMTuP9KXc63paR47bldacC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'i5ydMupPxxWMTuP9KXc63paR47bldacC',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 20,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Hazards',
    'visibility' => 0,
  );

  $export['facetapi-kA0uA00eH8nUOEUpUzqrudmTMrpfYM0V'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'kA0uA00eH8nUOEUpUzqrudmTMrpfYM0V',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 22,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Health effects',
    'visibility' => 0,
  );

  $export['facetapi-lflhfumXFA1jHdQKRm3gckIOmwADtTkV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lflhfumXFA1jHdQKRm3gckIOmwADtTkV',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 30,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Purpose of the material',
    'visibility' => 0,
  );

  $export['facetapi-mgmRoip1sH4Hg97gFVC3zsm2dzmIYGR9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'mgmRoip1sH4Hg97gFVC3zsm2dzmIYGR9',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 26,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Worker groups',
    'visibility' => 0,
  );

  $export['facetapi-tN10RR1GhTwEjOu0qZRhPRkfCe4HJKdy'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tN10RR1GhTwEjOu0qZRhPRkfCe4HJKdy',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 24,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Prevention measures',
    'visibility' => 0,
  );

  $export['facetapi-zjhTXjlZM2tx82i0zG20DKexKaoVXirW'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zjhTXjlZM2tx82i0zG20DKexKaoVXirW',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'osha_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'osha_admin',
        'weight' => 0,
      ),
      'osha_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'osha_frontend',
        'weight' => 28,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of visual resource',
    'visibility' => 0,
  );

  return $export;
}
