<?php

/**
 * @file
 * Implements eu CAPTCHA for use with the CAPTCHA module
 */

/**
 * Implements hook_menu().
 */
//function eu_captcha_menu() {
//  $items = array();
//  $items['admin/config/people/captcha/eu_captcha'] = array(
//    'title' => 'EU CAPTCHA',
//    'file' => 'eu_captcha.admin.inc',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('eu_captcha_settings_form'),
//    'access arguments' => array('administer CAPTCHA settings'),
//    'type' => MENU_LOCAL_TASK,
//  );
//  return $items;
//}

/**
 * Implements hook_captcha().
 */
function eu_captcha_captcha($op, $captcha_type = '') {
  switch ($op) {
    case 'list':
      return array('EUCAPTCHA');

    case 'generate':
      if ($captcha_type == 'EUCAPTCHA') {
        drupal_add_js('https://europa.eu/webtools/load.js', array('defer' => TRUE, 'async' => TRUE, 'type' => 'external'));
        $result['captcha_validate'] = 'eu_captcha_validation';
        $result['solution'] = TRUE;
        $result['form']['captcha_image'] = array(
          '#weight' => -1,
          '#type' => 'markup',
          '#markup' => '<script type="application/json">{"service": "captcha"}</script>',
        );
        return $result;
      }
      break;
  }
}

/**
 * Implements hook_validate().
 */
function eu_captcha_validation() {
  if (isset($_REQUEST['wt_captcha_answer']) && isset($_REQUEST['wt_captcha_sid'])) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,"https://europa.eu/webtools/rest/captcha/verify.php");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS,
      "sid=" . $_REQUEST['wt_captcha_sid'] . "&answer=" . $_REQUEST['wt_captcha_answer']);

    curl_setopt($ch, CURLOPT_FILETIME, TRUE);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
    $content = curl_exec($ch);
    curl_close($ch);
    if (strpos($content, 'success')) {
      return TRUE;
    }
    return FALSE;
  }
  return FALSE;
}