<?php
/**
 * @file
 * Code for the OSHA Events feature.
 */

include_once 'osha_events.features.inc';

/**
 * Implements hook_admin_paths().
 */
function osha_events_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'node/*/event_moderation' => TRUE,
      'node/*/event_moderation/*/unpublish' => TRUE,
      'node/*/event_moderation/*/change-state/*' => TRUE,
      'node/*/event_moderation/view' => TRUE,
      'node/*/event_moderation/diff' => TRUE,
      'node/*/event_moderation/diff/list' => TRUE,
      'node/*/event_moderation/diff/view' => TRUE,
      'node/*/event_moderation/diff/view/*/*' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_menu().
 */
function osha_events_menu() {
  $items = array();
  // Display a node's moderation history
  $items["node/%node/event_moderation"] = array(
    'title' => 'Moderate',
    'description' => 'Show the content moderation history.',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'osha_events_moderation_node_history_view',
    'page arguments' => array(1),
    'access callback' => '_osha_events_moderation_access',
    'access arguments' => array('view history', 1),
  );

  $items['node/%node/event_moderation/view'] = array(
    'title' => 'Revisions',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  // If the diff module is present, replicate its pages under the moderation tab.
  if (module_exists('diff')) {
    $diff_menu_items  = diff_menu();

    $items['node/%node/event_moderation/diff'] = array(
      'type' => MENU_LOCAL_TASK,
      'file path' => drupal_get_path('module', 'diff'),
      'title' => 'Compare revisions',
      'page arguments' => array(1),
    );

    $items['node/%node/event_moderation/diff'] += $diff_menu_items['node/%node/revisions/list'];


    $items['node/%node/event_moderation/diff/list'] = array(
      'title' => 'Compare revisions',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -1,
    );

    $items['node/%node/event_moderation/diff/view'] = array(
      'page arguments' => array(1, 5, 6),
      'tab_parent' => 'node/%/event_moderation/diff/list',
      'file path' => drupal_get_path('module', 'diff'),
    );

    $items['node/%node/event_moderation/diff/view'] += $diff_menu_items['node/%node/revisions/view'];
    $items['node/%node/event_moderation/diff']['page callback'] = 'osha_events_diffs_overview';
    $items['node/%node/event_moderation/diff/view']['page callback'] = 'osha_events_diffs_show';
  }

  return $items;
}

function osha_events_diffs_overview($node) {
  drupal_set_title(t('Revisions for %title', array('%title' => $node->title)), PASS_THROUGH);
  $form = drupal_get_form('diff_node_revisions', $node);
  foreach($form['operations'] as $k => $v) {
    if (!is_array($v)) {
      continue;
    }
    if (!empty($v[0]) && is_array($v[0]) && strpos($v['0']['#markup'], '/revert')) {
      $form['operations'][$k][0]['#markup'] = '';
    }
  }
  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter.
 */
function osha_events_form_diff_node_revisions_alter(&$form, &$form_state, $form_id) {
  // If this form is appearing under moderation then add a submit function
  // that will keep the user in the moderation tab.
  if (arg(2) == 'event_moderation') {
    $form['#submit'][] = 'osha_events_diff_node_revisions_submit';
  }
}

/**
 * Redirects the the diff_node_revisions form when the user is under the moderation tab.
 */
function osha_events_diff_node_revisions_submit($form, &$form_state) {
  // the ids are ordered so the old revision is always on the left
  $old_vid = min($form_state['values']['old'], $form_state['values']['new']);
  $new_vid = max($form_state['values']['old'], $form_state['values']['new']);
  $form_state['redirect'] =  'node/'. $form_state['values']['nid'] .'/event_moderation/diff/view/'. $old_vid .'/'. $new_vid;
}

/**
 * Custom access handler for node operations.
 *
 * @param $op
 *   The operation being requested.
 * @param $node
 *   The node being acted upon.
 *
 * @return
 *   Boolean TRUE or FALSE.
 */
function _osha_events_moderation_access($op, $node) {
  global $user;

  //  // If we do not control this node type, deny access.
  if ($node->type != 'events') {
    return FALSE;
  }
  $access = TRUE;

  // The user must be able to view the moderation history.
  $access &= user_access('view moderation history');

  // The user must be able to edit this node.
  $access &= node_access('update', $node);
  return $access;
}

function osha_events_moderation_access_link($text, $internal_path, $options = array()) {
  if (($item = menu_get_item($internal_path)) && !empty($item['access'])) {
    return l($text, $internal_path, $options);
  }
}

function osha_events_diffs_show($node, $old_vid, $new_vid, $state = NULL) {
  // Attaches the CSS.
  $build['#attached'] = diff_build_attachments();

  $default_state = variable_get('diff_default_state_node', 'raw');
  if (empty($state)) {
    $state = $default_state;
  }
  $state = str_replace('-', '_', $state);
  if (!array_key_exists($state, diff_available_states())) {
    $state = $default_state;
  }

  // Same title as the 'Revisions' tab. Blocked by non-page requests.
  if (node_is_page($node)) {
    drupal_set_title(t('Revisions for %title', array('%title' => $node->title)), PASS_THROUGH);
  }
  $node_revisions = node_revision_list($node);

  $old_node = node_load($node->nid, $old_vid);
  $new_node = node_load($node->nid, $new_vid);

  // Generate table header (date, username, log message).
  $old_header = t('!date by !username', array(
    '!date' => l(format_date($old_node->revision_timestamp), "node/$node->nid/revisions/$old_node->vid/view", array('absolute' => 1)),
    '!username' => theme('username', array('account' => $node_revisions[$old_vid])),
  ));
  $new_header = t('!date by !username', array(
    '!date' => l(format_date($new_node->revision_timestamp), "node/$node->nid/revisions/$new_node->vid/view", array('absolute' => 1)),
    '!username' => theme('username', array('account' => $node_revisions[$new_vid])),
  ));

  $old_log = $old_node->log != '' ? '<p class="revision-log">' . filter_xss($old_node->log) . '</p>' : '';
  $new_log = $new_node->log != '' ? '<p class="revision-log">' . filter_xss($new_node->log) . '</p>' : '';

  // Generate previous diff/next diff links.
  $nav_suffix = ($default_state != $state) ? '/' . str_replace('_', '-', $state) : '';
  $next_vid = _diff_get_next_vid($node_revisions, $new_vid);
  if ($next_vid) {
    $next_link = l(t('Next difference >'), 'node/' . $node->nid . '/revisions/view/' . $new_vid . '/' . $next_vid . $nav_suffix, array('absolute' => 1));
  }
  else {
    $next_link = '';
  }
  $prev_vid = _diff_get_previous_vid($node_revisions, $old_vid);
  if ($prev_vid) {
    $prev_link = l(t('< Previous difference'), 'node/' . $node->nid . '/revisions/view/' . $prev_vid . '/' . $old_vid . $nav_suffix, array('absolute' => 1));
  }
  else {
    $prev_link = '';
  }

  $header = _diff_default_header($old_header, $new_header);
  $rows = array();
  if ($old_log || $new_log) {
    $rows['logs'] = array(
      array(
        'data' => $old_log,
        'colspan' => 2,
      ),
      array(
        'data' => $new_log,
        'colspan' => 2,
      ),
    );
  }
  $rows['navigation'] = array(
    array(
      'data' => $prev_link,
      'class' => array('diff-prevlink'),
      'colspan' => 2,
    ),
    array(
      'data' => $next_link,
      'class' => array('diff-nextlink'),
      'colspan' => 2,
    ),
  );

  $links = array();
  foreach (diff_available_states('node') as $alternative_state => $label) {
    if ($alternative_state == $state) {
      // @todo: Should we show both or just alternatives?
    }
    $links[$alternative_state] = array(
      'title' => $label,
      'href' => "node/{$node->nid}/revisions/view/{$old_vid}/{$new_vid}" . ($alternative_state == $default_state ? '' : '/' . str_replace('_', '-', $alternative_state)),
    );
  }
  if (count($links) > 1) {
    $state_links = theme('links', array(
      'links' => $links,
      'attributes' => array('class' => array('links', 'inline')),
    ));
    $rows['states'] = array(
      array(
        'data' => $state_links,
        'class' => 'diff-links',
        'colspan' => 4,
      ),
    );
  }
  $rows = array_merge($rows, _diff_body_rows($old_node, $new_node, $state));

  $build['diff_table'] = array(
    '#theme' => 'table__diff__standard',
    '#header' => $header,
    '#rows' => $rows,
    '#attributes' => array('class' => array('diff')),
    '#colgroups' => _diff_default_cols(),
    '#sticky' => FALSE,
  );

  // Allow users to hide or set the display mode of the preview.
  if (node_is_page($node) && $view_mode = variable_get('diff_view_mode_preview_node_' . $new_node->type, 'full')) {
    $header = '';
    if ($node->vid == $new_vid) {
      $header .= '<div class="diff-section-title">' . t('Current revision:') . '</div>';
    }
    else {
      $header .= '<div class="diff-section-title">' . t('Revision of @new_date:', array('@new_date' => format_date($new_node->revision_timestamp))) . '</div>';
    }
    $build['diff_preview']['header']['#markup'] = $header;
    // Don't include node links or comments when viewing the diff.
    $build['diff_preview']['content'] = node_view($new_node, $view_mode);
    if (isset($build['diff_preview']['content']['links'])) {
      unset($build['diff_preview']['content']['links']);
    }
    if (isset($build['diff_preview']['content']['comments'])) {
      unset($build['diff_preview']['content']['comments']);
    }
  }
  return $build;
}

/**
 * Display a node's moderation history.
 *
 * @param $node
 *   The node being acted upon.
 *
 * @return
 *   A themed table of data and links for node moderation actions.
 */
function osha_events_moderation_node_history_view($node) {
  global $user;
  // Page title.
  drupal_set_title(t('History of %title', array('%title' => $node->title)), PASS_THROUGH);

  // Get all of the node revisions, each with its most recent moderation.
  $query = db_select('node', 'n')->extend('PagerDefault');
  $query->leftJoin('node_revision', 'r', 'n.nid = r.nid');
  $query->leftJoin('users', 'u', 'r.uid = u.uid');
  $query->addField('n', 'vid', 'live_revision');
  $query->condition('n.nid', $node->nid)
    ->orderBy('r.vid', 'DESC')
    ->fields('r', array('nid', 'vid', 'title', 'log', 'uid', 'timestamp'))
    ->fields('u', array('name'))
    ->limit(30);

  $revisions = $query->execute()
    ->fetchAllAssoc('vid');

  // Build the table rows.
  $rows = array();
  foreach ($revisions as $revision) {
    $row = array(
      'data' => array(
        'vid' => '',
        'info' => '',
        'date' => '',
        'revision' => '',
      ),
      'class' => array('revision'),
    );

    // Add row classes.
    if ($revision->vid == $node->workbench_moderation['current']->vid) {
      $row['class'][] = 'current-revision';
    }
    if (isset($node->workbench_moderation['published']) && $revision->vid == $node->workbench_moderation['published']->vid) {
      $row['class'][] = 'published-revision';
    }
    else {
      $row['class'][] = 'unpublished-revision';
    }

    // Add row data.
    $row['data']['vid'] = $revision->vid;
    $row['data']['info'] .= '<div class="revision-title">' . check_plain($revision->title) . '</div>';
    $row['data']['info'] .= '<div class="revision-log description">' . filter_xss($revision->log) . '</div>';
    $row['data']['info'] .= '<div class="revision-user description">' . t('Revised by !user', array('!user' => theme('username', array('account' => $revision)))) . '</div>';
    $row['data']['date'] = format_date($revision->timestamp, 'short');

    // Revision operations.
    $revision_operations = array();
    if (isset($node->workbench_moderation['published']) && $revision->vid == $node->workbench_moderation['published']->vid) {
      $revision_operations['view'] = osha_events_moderation_access_link(t('view'), "node/{$revision->nid}");
    }
    elseif ($revision->vid == $node->workbench_moderation['current']->vid) {
      $revision_operations['view'] = osha_events_moderation_access_link(t('view'), "node/{$revision->nid}/current-revision");
    }
    else {
      $revision_operations['view'] = osha_events_moderation_access_link(t('view'), "node/{$revision->nid}/revisions/{$revision->vid}/view");
    }

    $revision_operations['delete'] = osha_events_moderation_access_link(t('delete'), "node/{$revision->nid}/revisions/{$revision->vid}/delete");

    $row['data']['revision'] = implode(' | ', array_filter($revision_operations));
    $rows[] = $row;
  }

  // Set the table header.
  $header = array(t('Revision'), t('Title'), t('Date'), t('Revision actions'));

  // Return properly styled output.
  $build['pager_table'] = array(
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'workbench_moderation') . '/css/workbench_moderation.css',
      ),
    ),
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );

  // Attach the pager theme.
  $build['pager_pager'] = array('#theme' => 'pager');

  return $build;
}

/**
 * Implements hook_node_access().
 */
function osha_events_node_access($node, $op, $account) {
  if ($op == 'view' && $node->status == 0 && $node->type == 'events' && user_access('edit any events content')) {
    return NODE_ACCESS_ALLOW;
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * {@inheritdoc}
 */
function osha_field_widget_form_alter(&$element, &$form_state, $context) {
  $is_edit_form = (isset($context['form']['#node_edit_form']) && $context['form']['#node_edit_form'] == TRUE);
  $is_events_form = $is_edit_form && ($context['form']['type']['#value'] == 'events');
  if ($is_events_form && !empty($element['#field_name'])) {
    switch ($element['#field_name']) {
      case 'field_organization':
        $placeholder = t('The name of the organisation');
        $element['value']['#attributes']['placeholder'] = $placeholder;
        break;
      case 'field_city':
        $placeholder = t('Event city');
        $element['value']['#attributes']['placeholder'] = $placeholder;
        break;
      case 'field_location':
        $placeholder = 'Location of the event, e.g. name of venue, hall, hotel.';
        $element['value']['#attributes']['placeholder'] = $placeholder;
        break;
    }
  }
}

function _form_add_website_placeholder_after_build($form) {
  $placeholder = t('Website of event');
  $form['field_website_of_event'][LANGUAGE_NONE][0]['url']['#attributes']['placeholder'] = $placeholder;
  drupal_add_js(drupal_get_path('module', 'osha') . '/js/jquery.charactersRemaining.js');
  drupal_add_js(drupal_get_path('module', 'osha') . '/js/charactersRemaining.js', array('scope' => 'footer'));
  return $form;
}

/**
 * Implements hook_block_info().
 */
function osha_events_block_info() {
  $blocks = array();
  $blocks['osha_events_dates'] = array(
    'info' => t('events filter dates'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_search_api_solr_query_alter().
 */
function osha_events_search_api_solr_query_alter(array &$call_args, SearchApiQueryInterface $query) {
  if (arg(0) == 'oshevents') {
    if (!isset($_REQUEST['field_start_date_value'])) {
      $fq = variable_get('solr_event_start_date_fq', 'ds_field_start_date\:value:');
      if ($fq) {
        $call_args['params']['fq'][] = $fq . '["' . date("Y-m-d\TH:i:s") . 'Z" TO *]';
      }
    }
  }
  $field_start_date = variable_get('oshevents_field_start_date', 'field_start_date\:value:');
  foreach($call_args['params']['fq'] as &$fq) {
    if (strpos($fq, $field_start_date)) {
      $fq = '(' . $fq . ') OR (' . str_replace(':value:',':value2:', $fq) . ')';
    }
  }
  foreach($call_args['params']['fq'] as &$fq) {
    if (strpos($fq, 'field_start_date$value')) {
      $fq = '(' . $fq . ') OR (' . str_replace('$value','$value2', $fq) . ')';
    }
  }
}

function osha_events_dates_form($form, $form_state) {
  $form = array();
  $form['#prefix'] = '<div class="content-filters">';
  $form['#suffix'] = '</div>';
  $date_format = 'd/m/Y';
  $form['from_date'] = array(
    '#type' => 'date_popup',
    '#date_format'=> $date_format,
    '#date_year_range' => '-3:+3',
    '#title' => t('From date'),
    '#attributes' => ['class' => ['new-select-style']],
  );
  $form['to_date'] = array(
    '#type' => 'date_popup',
    '#date_format'=> $date_format,
    '#date_year_range' => '-3:+3',
    '#title' => t('To date'),
    '#attributes' => ['class' => ['new-select-style']],
  );
  if (!empty($_REQUEST['field_start_date_value'])) {
    $date = explode('/', $_REQUEST['field_start_date_value']['date']);
    $form['from_date']['#default_value'] = $date[2] . '-' . $date[1] . '-' . $date[0];
  }
  else {
    $form['from_date']['#default_value'] = date('Y-m-d');
  }
  if (!empty($_REQUEST['field_start_date_value2'])) {
    $date = explode('/', $_REQUEST['field_start_date_value2']['date']);
    $form['to_date']['#default_value'] = $date[2] . '-' . $date[1] . '-' . $date[0];
  }
  return $form;
}

/**
 * Implements hook_block_view().
 */
function osha_events_block_view($delta = '') {
  $block = array();
  if ($delta == 'osha_events_dates') {
    drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/auto-submit.js', array('weight' => 20));
    drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/filter_dates.js', array('weight' => 20));
    $block['content'] = drupal_get_form('osha_events_dates_form');
  }
  return $block;
}

/**
 * Implements hook_form_alter().
 */
function osha_events_form_alter(&$form, &$form_state, $form_id) {
  if (($form_id == 'views_exposed_form') && ($form['#id'] == 'views-exposed-form-newevents-page')) {
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search in resources');
    $form['search_api_views_fulltext']['#attributes']['class'][] = 'search-new-design';

    $form['sort_by']['#attributes']['class'][] = 'new-select-style';
    $form['field_country_code']['#attributes']['class'][] = 'new-select-style';
    $form['field_country_code']['#chosen'] = TRUE;
  }
  $is_edit_form = isset($form['#node_edit_form']) && $form['#node_edit_form'] == TRUE;
  $is_events_form = $is_edit_form && $form['type']['#value'] == 'events';
  if ($is_events_form) {
    $form['#after_build'] = array('_form_add_website_placeholder_after_build');
  }
  switch ($form_id) {
    case 'events_node_form':
      $form['field_agency_initial_contact']['#access'] = FALSE;
      $form['field_satisfaction_rate']['#access'] = FALSE;
      $form['field_event_in_amp']['#access'] = FALSE;
      $form['field_agency_contact_reply']['#access'] = FALSE;
      $form['field_number_of_attendees']['#access'] = FALSE;
      $form['field_organized_by_eu_osha']['#access'] = FALSE;

      $form['#validate'][] = 'osha_events_form_validate';
      // Activity field changes.
      if (isset($form['field_activity'][LANGUAGE_NONE][0])) {
        unset($form['field_activity'][LANGUAGE_NONE]['add_more']);
        // Extract the field field tree to change cardinality.
        $field = $form['field_activity'][LANGUAGE_NONE][0]['tid'];

        // Show the label as usual.
        unset($field['#title_display']);

        $field['#options'] = array('' => t('- None -')) + $field['#options'];
        // Switch validator.
        $field['#element_validate'] = array('options_field_widget_validate');

        $form['field_activity'][LANGUAGE_NONE] = $field;
      }

      // Create new event form.
      if (!isset($form['#node']->nid)) {
        drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/new_event_form.js');
      }

      // MC-84 Disable country and city from the form when selected type is Webminar.
      // Necessary to add the js in an after build callback because we need it
      // after form_set_error occurs.
      $form['#after_build'][] = 'osha_events_node_form_after_build';
      break;

    case 'views_exposed_form':
      if (in_array($form['#id'], array('views-exposed-form-events-page'))) {
        // Set default date for popup on end date when start date is selected.
        $form['field_start_date_value2']['value']['#attached']['js'] = array(
          drupal_get_path('module', 'osha_events') . '/js/event_search_page.js' => array(
            'type' => 'file',
          ),
        );

        if (!empty($form_state['input']['field_start_date_value']['value']['date']) && empty($form_state['input']['field_start_date_value2']['value']['date'])) {
          $form['field_start_date_value2']['value']['#datepicker_options']['defaultDate'] = $form_state['input']['field_start_date_value']['value']['date'];
        }
      }
      break;
  }
}

/**
 * After build callback for events_node_form.
 */
function osha_events_node_form_after_build($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/event_form.js');

  if ($form_state['values']['status'] == 1) {
    drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/published_event_form.js');
  }

  return $form;
}

/**
 * Validation callback.
 */
function osha_events_form_validate($form, &$form_state) {
  // When publishing an event, some fields are required.
  $values = $form_state['values'];
  $node = $form_state['node'];
  $type = $values['field_event_type'][LANGUAGE_NONE][0]['value'];
  if ($values['status'] == 1) {
    if (empty($type) || $type == 'Visit') {
      form_set_error('field_event_type', 'Events of type <b>Visit</b> can not be published');
    }
    if (empty($values['field_organization'][LANGUAGE_NONE][0]['value'])) {
      //      form_set_error('field_organization', 'You have to add an Organization.');
    }

    if (empty($values['field_tags'][LANGUAGE_NONE][0]['tid'])) {
      form_set_error('field_tags', 'You have to add a Category / Tag.');
    }

    if ($values['field_for_the_web'][LANGUAGE_NONE][0]['value'] != 'Yes') {
      form_set_error('field_for_the_web', 'Event is not for web publishing. To override, set field "For the web / Public" to "Yes".');
    }
  }

  // Country and city are not required for webminar events.
  //  if ($type == 'Webminar') {
  // Country and city fields need to be NULL for webminar events so that
  // they will not show in frontend.
  //    form_set_error('field_city', '', array());
  //    form_set_error('field_country_code', '', array());
  //    $form_state['values']['field_country_code'][LANGUAGE_NONE][0]['value'] = $form_state['values']['field_city'][LANGUAGE_NONE][0]['value'] = NULL;
  //  }
  //  else {
  if (empty($values['field_country_code'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('field_country_code', 'Country field is required.');
  }
  if (empty($values['field_city'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('field_city', 'City field is required.');
  }
  //  }

  // Check if the event is unique by Start and End Date field.
  $start_date = $form_state['values']['field_start_date']['und'][0]['value'];
  $end_date = $form_state['values']['field_start_date']['und'][0]['value2'];

  $query = new EntityFieldQuery;
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'events')
    ->fieldCondition('field_start_date', 'value', $start_date, '=')
    ->fieldCondition('field_start_date', 'value2', $end_date, '=')
    ->entityOrderBy('entity_id', 'DESC');
  if (isset($node->nid)) {
    $query->entityCondition('entity_id', $node->nid, '!=');
  }
  $results = $query->execute();

  if (isset($results['node']) && count($results['node']) >= 1) {
    drupal_set_message(t('One or more events have the same Start and End date.'), 'warning');
    $events = '';
    foreach ($results['node'] as $nid => $node_obj) {
      $node = node_load($nid);
      $events .= l($node->title, 'node/' . $nid);
      $events .= '<br />';
    }
    drupal_set_message($events, 'warning');
  }
}

function osha_events_views_pre_render(&$view) {
  if ($view->name == 'newevents') {
    drupal_add_js(array('osha_events' => array('add_to_calendar' => t('Add to my calendar'))), 'setting');
    drupal_add_js(drupal_get_path('module', 'osha_events') . '/js/ouical.min.js');
  }
}

function osha_events_query_alter($query) {

  if ($query->hasTag('debug')) {
    $sql = (string)$query;
    $connection = Database::getConnection();
    foreach ((array) $query->arguments() as $key => $val) {
      $quoted[$key] = $connection->quote($val);
    }
    $sql = strtr($sql, $quoted);
    dpm($sql);
  }
}


/**
 * Altering Date Popup to remove labels and description for specific field
 */
function osha_events_date_popup_process_alter(&$element, &$form_state, $context) {
  if ($element['#name'] == 'field_start_date_value' || $element['#name'] == 'field_start_date_value2') {
    //unset($element['date']['#description']);
    unset($element['date']['#title']);
  }
  if ($element['#name'] == 'from_date' || $element['#name'] == 'to_date') {
    unset($element['date']['#description']);
    unset($element['date']['#title']);
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_events_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_events', 'osha_events.translations');
  return osha_events_get_translatable_strings();
}


/**
 * Implements hook_user_role_insert().
 */
function osha_events_user_role_insert($role) {
  if ($role->name == 'Events Editor') {
    user_role_grant_permissions($role->rid, array(
      'access contextual links',
      'access dashboard',

      'create files',
      'view own private files',
      'view own files',
      'view files',

      'edit own image files',
      'edit any image files',
      'delete own image files',
      'download own image files',
      'download any image files',

      'use text format full_html',
      'use text format filtered_html',

      'access media browser',

      'edit meta tags',
      'access content',
      'view own unpublished content',
      'view revisions',

      'create events content',
      'edit own events content',
      'edit any events content',

      'create url aliases',
      'access administration pages',
      'view the administration theme',
    ));
  }
}

/**
 * Implements hook_phpexcel_export().
 */
function osha_events_phpexcel_export($op, &$data, &$phpexcel, $options, $column = NULL, $row = NULL) {
  $xls_colours = array(
    'Black' => '000000',
    'Red' => 'FF0000',
    'Grey' => '808080',
    'Yellow' => 'FFFF00',
    'Green' => '008000',
    'Blue' => '0000FF',
  );
  switch ($op) {
    case 'post cell':
      if ($row == 1) {
        // First row.
        $styleArray = array('font' => array('bold' => TRUE));
        $phpexcel->getStyleByColumnAndRow($column, $row)->applyFromArray($styleArray);
      }
      else {
        // Use the color named in the first cell of the current row.
        $first_cell = $phpexcel->getCellByColumnAndRow(0, $row)->getValue();
        if (!empty($xls_colours[$first_cell])) {
          $styleArray = array(
            'font'  => array(
              'color' => array('rgb' => $xls_colours[$first_cell]),
            ),
          );
          $phpexcel->getStyleByColumnAndRow($column, $row)->applyFromArray($styleArray);
        }
      }
      break;
  }
}

/**
 * Implements hook_element_info_alter()
 */
function osha_events_element_info_alter(&$type) {
  if (isset($type['link_field'])) {
    $type['link_field']['#process'][] = 'osha_events_link_field_process';
  }
}

/**
 * Change field label.
 */
function osha_events_link_field_process($element, $form_state, $complete_form) {
  switch ($element['#field_name']) {
    case 'field_website_of_event':
      $element['title']['#title'] = t('Website name');
      $element['url']['#title'] = t('Website url');
      break;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_info().
 */
function osha_events_field_formatter_info() {
  $info = array(
    'translated_title_as_link' => array(
      'label' => 'Translated title, as link',
      'field types' => array('link_field'),
      'description' => 't(title) as link.',
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function osha_events_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'translated_title_as_link':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_events_translated_title_as_link_format',
          '#entity' => $entity,
          '#item' => $item,
          '#delta' => $delta,
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function osha_events_theme() {
  return array(
    'osha_events_translated_title_as_link_format' => array(
      'variables' => array('entity' => NULL, 'item' => NULL, 'delta' => NULL),
    ),
  );
}

/*
* Formats link as translated title
*/
function theme_osha_events_translated_title_as_link_format($element) {
  $item = $element['item'];
  if (empty($item['title'])) {
    $title = $item['display_url'];
  }
  else {
    $title = t($item['title']);
  }
  return l($title, $item['url'], array(
    'attributes' => $item['attributes'],
    'query' => $item['query'],
    'fragment' => $item['fragment'],
    'absolute' => $item['absolute'],
    'html' => $item['html'],
  ));
}
